// Generated By: LDView 4.4 Alpha 5 Copyright (C) 2019 Travis Cobbs & Peter Bartfai
// See: https://tcobbs.github.io/ldview/
// Date: Mon Jul  1 04:53:53 2019
// Input LDraw File: slope_test.ldr
// LDraw File Author: MLCad
//
// This file was automatically generated from an LDraw file by the program
// LDView.  See comments above for further details.

#version 3.7;

#if (version >= 3.7) global_settings {assumed_gamma 1} #end

#ifndef (LDXQual) #declare LDXQual = 3; #end	// Quality (0 = Bounding Box; 1 = No Refraction; 2 = Normal; 3 = Stud Logos)
#ifndef (LDXSW) #declare LDXSW = 0.5; #end	// Seam Width (0 for no seams)
#ifndef (LDXStuds) #declare LDXStuds = 1; #end	// Show studs? (1 = YES; 0 = NO)
#ifndef (LDXRefls) #declare LDXRefls = 1; #end	// Reflections? (1 = YES; 0 = NO)
#ifndef (LDXShads) #declare LDXShads = 1; #end	// Shadows? (1 = YES; 0 = NO)
#ifndef (LDXBackground) #declare LDXBackground = 0; #end	// Include Background? (1 = YES; 0 = NO)
#ifndef (LDXFloor) #declare LDXFloor = 0; #end	// Include Floor? (1 = YES; 0 = NO)

// Model bounds information
#ifndef (LDXMinX) #declare LDXMinX = -19.75; #end
#ifndef (LDXMinY) #declare LDXMinY = -27.75; #end
#ifndef (LDXMinZ) #declare LDXMinZ = -19.75; #end
#ifndef (LDXMaxX) #declare LDXMaxX = 19.75; #end
#ifndef (LDXMaxY) #declare LDXMaxY = -0.25; #end
#ifndef (LDXMaxZ) #declare LDXMaxZ = 19.75; #end
#ifndef (LDXCenterX) #declare LDXCenterX = 0; #end
#ifndef (LDXCenterY) #declare LDXCenterY = -14; #end
#ifndef (LDXCenterZ) #declare LDXCenterZ = 0; #end
#ifndef (LDXCenter) #declare LDXCenter = <LDXCenterX,LDXCenterY,LDXCenterZ>; #end
#ifndef (LDXRadius) #declare LDXRadius = 31.131777; #end

// Camera settings
#ifndef (LDXCameraLoc) #declare LDXCameraLoc = < 49.817265,-54.675625,-49.817265 >; #end	// Camera Location vector
#ifndef (LDXCameraLookAt) #declare LDXCameraLookAt = < -4.79366770383710161241,-10.08598699795276587565,4.79366770383710161241 >; #end	// Camera look-at point vector
#ifndef (LDXCameraSky) #declare LDXCameraSky = < -0.35355339491603171576,-0.8660254002549215846,0.35355339491603171576 >; #end	// Camera sky vector (<0,-1,0> will usually work for standard "up")
#ifndef (LDXCameraAngle) #declare LDXCameraAngle = 76.900337; #end
#ifndef (LDXCameraAspect) #declare LDXCameraAspect = image_width/image_height; #end
#ifndef (LDXCameraTransform) #declare LDXCameraTransform = transform {}; #end

#ifndef (LDXFloorLoc) #declare LDXFloorLoc = LDXMaxY; #end	// Floor location. (Dependent on floor axis; MAX_Y is bottom of model)
#ifndef (LDXFloorAxis) #declare LDXFloorAxis = y; #end	// Floor axis (x, y, or z)
#ifndef (LDXFloorR) #declare LDXFloorR = 0.8; #end	// Floor Red
#ifndef (LDXFloorG) #declare LDXFloorG = 0.8; #end	// Floor Green
#ifndef (LDXFloorB) #declare LDXFloorB = 0.8; #end	// Floor Blue
#ifndef (LDXFloorAmb) #declare LDXFloorAmb = 0.4; #end	// Floor Ambient
#ifndef (LDXFloorDif) #declare LDXFloorDif = 0.4; #end	// Floor Diffuse
#ifndef (LDXAmb) #declare LDXAmb = 0.4; #end
#ifndef (LDXDif) #declare LDXDif = 0.4; #end
#ifndef (LDXRefl) #declare LDXRefl = 0.08; #end
#ifndef (LDXPhong) #declare LDXPhong = 0.5; #end
#ifndef (LDXPhongS) #declare LDXPhongS = 40; #end
#ifndef (LDXTRefl) #declare LDXTRefl = 0.2; #end
#ifndef (LDXTFilt) #declare LDXTFilt = 0.85; #end
#ifndef (LDXIoR) #declare LDXIoR = 1.25; #end
#ifndef (LDXRubberRefl) #declare LDXRubberRefl = 0; #end
#ifndef (LDXRubberPhong) #declare LDXRubberPhong = 0.1; #end
#ifndef (LDXRubberPhongS) #declare LDXRubberPhongS = 10; #end
#ifndef (LDXChromeRefl) #declare LDXChromeRefl = 0.85; #end
#ifndef (LDXChromeBril) #declare LDXChromeBril = 5; #end
#ifndef (LDXChromeSpec) #declare LDXChromeSpec = 0.8; #end
#ifndef (LDXChromeRough) #declare LDXChromeRough = 0.01; #end
#ifndef (LDXOpaqueNormal) #declare LDXOpaqueNormal = normal { bumps 0.001 scale 0.5 }; #end
#ifndef (LDXTransNormal) #declare LDXTransNormal = normal { bumps 0.001 scale 0.5 }; #end
#ifndef (LDXIPov) #declare LDXIPov = 1; #end	// Use inline POV code from LDraw file? (1 = YES; 0 = NO)
#ifndef (LDXBgR) #declare LDXBgR = 0.752941; #end	// Background Red
#ifndef (LDXBgG) #declare LDXBgG = 0.752941; #end	// Background Green
#ifndef (LDXBgB) #declare LDXBgB = 0.752941; #end	// Background Blue
#ifndef (LDXOrigVer) #declare LDXOrigVer = version; #end	// DO NOT MODIFY

// Camera
#ifndef (LDXSkipCamera)
camera {
	location LDXCameraLoc
	sky LDXCameraSky
	right LDXCameraAspect * < -1,0,0 >
	look_at LDXCameraLookAt
	angle LDXCameraAngle
	transform {LDXCameraTransform}
}
#end

// Lights
#ifndef (LDXSkipLight1)
light_source {	// Latitude,Longitude: 45,0,LDXRadius*2
	<0*LDXRadius,-1.414214*LDXRadius,-1.414214*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight2)
light_source {	// Latitude,Longitude: 30,120,LDXRadius*2
	<1.5*LDXRadius,-1*LDXRadius,0.866026*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight3)
light_source {	// Latitude,Longitude: 60,-120,LDXRadius*2
	<-0.866025*LDXRadius,-1.732051*LDXRadius,0.5*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end

#macro LDXSeamMatrix(Width, Height, Depth, CenterX, CenterY, CenterZ)
#local aw = 0;
#local ah = 0;
#local ad = 0;
#local ax = 0;
#local ay = 0;
#local az = 0;
#if (Width != 0)
#local aw = 1-LDXSW/Width;
#end
#if (Height != 0)
#local ah = 1-LDXSW/Height;
#end
#if (Depth != 0)
#local ad = 1-LDXSW/Depth;
#end
#if (Width != 0 & CenterX != 0)
#local ax = LDXSW/(Width / CenterX);
#end
#if (Height != 0 & CenterY != 0)
#local ay = LDXSW/(Height / CenterY);
#end
#if (Depth != 0 & CenterZ != 0)
#local az = LDXSW/(Depth / CenterZ);
#end
#if (aw <= 0)
#local aw = 1;
#local ax = 0;
#end
#if (ah <= 0)
#local ah = 1;
#local ay = 0;
#end
#if (ad <= 0)
#local ad = 1;
#local az = 0;
#end
matrix <aw,0,0,0,ah,0,0,0,ad,ax,ay,az>
#end


#if (LDXBackground != 0)
#if (version >= 3.7)
background { color srgb <LDXBgR,LDXBgG,LDXBgB> }
#else
background { color rgb <LDXBgR,LDXBgG,LDXBgB> }
#end
#end

#declare lg_quality = LDXQual;
#if (lg_quality = 3)
#declare lg_quality = 4;
#end

#declare lg_studs = LDXStuds;


#include "lg_defs.inc"

#include "lg_color.inc"

#ifndef (LDXColor1) // Blue
#declare LDXColor1 = #if (version >= 3.1) material { #end
	texture {
		lg_blue
	}
#if (version >= 3.1) } #end
#declare LDXColor1_slope = #if (version >= 3.1) material { #end
	texture {
		lg_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor7) // Light Grey
#declare LDXColor7 = #if (version >= 3.1) material { #end
	texture {
		lg_grey
	}
#if (version >= 3.1) } #end
#declare LDXColor7_slope = #if (version >= 3.1) material { #end
	texture {
		lg_grey
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#include "lg_3039.inc" // Slope Brick 45  2 x  2

#declare LDX_slope_test_dot_ldr = union {
// Untitled
// Name: slope_test.ldr
// Author: MLCad
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3039
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3039_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor1_slope }
	}
#if (LDXRefls = 0)
	no_reflection
#end
#if (LDXShads = 0)
	no_shadow
#end
}

// slope_test.ldr
object {
	LDX_slope_test_dot_ldr
	#if (version >= 3.1) material #else texture #end { LDXColor7 }
}

// Floor
#if (LDXFloor != 0)
object {
	plane { LDXFloorAxis, LDXFloorLoc hollow }
	texture {
#if (version >= 3.7)
		pigment { color srgb <LDXFloorR,LDXFloorG,LDXFloorB> }
#else
		pigment { color rgb <LDXFloorR,LDXFloorG,LDXFloorB> }
#end
		finish { ambient LDXFloorAmb diffuse LDXFloorDif }
	}
}
#end

