// This work is licensed under the Creative Commons Attribution-Share Alike 4.0 
// Unported License. To view a copy of this license, visit 
// https://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative 
// Commons, 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
// 
// Generated By: LDView 4.2 Copyright (C) 2008 Travis Cobbs & Peter Bartfai
// See: http://ldview.sourceforge.net/
// Date: Mon Sep 05 18:52:00 2016
// Input LDraw File: ldr_manned_mech_new.mpd
// LDraw File Author: MLCad
//
// This file was automatically generated from an LDraw file by the program
// LDView.  See comments above for further details.

#version 3.6;

#declare LDXQual = 3;	// Quality (0 = Bounding Box; 1 = No Refraction; 2 = Normal; 3 = Stud Logos)
#declare LDXSW = 0.5;	// Seam Width (0 for no seams)
#declare LDXStuds = 1;	// Show studs? (1 = YES; 0 = NO)
#declare LDXRefls = 1;	// Reflections? (1 = YES; 0 = NO)
#declare LDXShads = 1;	// Shadows? (1 = YES; 0 = NO)
#declare LDXFloor = 1;	// Include Floor? (1 = YES; 0 = NO)

// Model bounds information
#declare LDXMinX = -158.663986;
#declare LDXMinY = -463.92804;
#declare LDXMinZ = -87.459991;
#declare LDXMaxX = 180.274506;
#declare LDXMaxY = 2.000101;
#declare LDXMaxZ = 70.549103;
#declare LDXCenterX = 10.80526;
#declare LDXCenterY = -230.963974;
#declare LDXCenterZ = -8.455444;
#declare LDXCenter = <LDXCenterX,LDXCenterY,LDXCenterZ>;
#declare LDXRadius = 255.706161;

// Camera settings
#declare LDXCameraLoc = < 419.987885,-565.060181,-417.638062 >;	// Camera Location vector
#declare LDXCameraLookAt = < -81.299605426822438,-155.7606739545605,83.649428424869313 >;	// Camera look-at point vector
#declare LDXCameraSky = < -0.35355339491603172,-0.86602540025492158,0.35355339491603172 >;	// Camera sky vector (<0,-1,0> will usually work for standard "up")

#declare LDXFloorLoc = LDXMaxY;	// Floor location. (Dependent on floor axis; MAX_Y is bottom of model)
#declare LDXFloorAxis = y;	// Floor axis (x, y, or z)
#declare LDXFloorR = 0.8;	// Floor Red
#declare LDXFloorG = 0.8;	// Floor Green
#declare LDXFloorB = 0.8;	// Floor Blue
#declare LDXFloorAmb = 0.4;	// Floor Ambient
#declare LDXFloorDif = 0.4;	// Floor Diffuse
#declare LDXAmb = 0.4;
#declare LDXDif = 0.4;
#declare LDXRefl = 0.08;
#declare LDXPhong = 0.5;
#declare LDXPhongS = 40;
#declare LDXTRefl = 0.2;
#declare LDXTFilt = 0.85;
#declare LDXIoR = 1.25;
#declare LDXRubberRefl = 0;
#declare LDXRubberPhong = 0.1;
#declare LDXRubberPhongS = 10;
#declare LDXChromeRefl = 0.85;
#declare LDXChromeBril = 5;
#declare LDXChromeSpec = 0.8;
#declare LDXChromeRough = 0.01;
#declare LDXIPov = 1;	// Use inline POV code from LDraw file? (1 = YES; 0 = NO)
#declare LDXBgR = 0.752941;	// Background Red
#declare LDXBgG = 0.752941;	// Background Green
#declare LDXBgB = 0.752941;	// Background Blue
#declare LDXOrigVer = version;	// DO NOT MODIFY

// Camera
#ifndef (LDXSkipCamera)
camera {
	#declare LDXCamAspect = 4/3;
	location LDXCameraLoc
	sky LDXCameraSky
	right LDXCamAspect * < -1,0,0 >
	look_at LDXCameraLookAt
	angle 57.822403
}
#end

// Lights
#ifndef (LDXSkipLight1)
light_source {	// Latitude,Longitude: 45,0,LDXRadius*2
	<0*LDXRadius,-1.414214*LDXRadius,-1.414214*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight2)
light_source {	// Latitude,Longitude: 30,120,LDXRadius*2
	<1.5*LDXRadius,-1*LDXRadius,0.866026*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight3)
light_source {	// Latitude,Longitude: 60,-120,LDXRadius*2
	<-0.866025*LDXRadius,-1.732051*LDXRadius,0.5*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end

#macro LDXSeamMatrix(Width, Height, Depth, CenterX, CenterY, CenterZ)
#local aw = 0;
#local ah = 0;
#local ad = 0;
#local ax = 0;
#local ay = 0;
#local az = 0;
#if (Width != 0)
#local aw = 1-LDXSW/Width;
#end
#if (Height != 0)
#local ah = 1-LDXSW/Height;
#end
#if (Depth != 0)
#local ad = 1-LDXSW/Depth;
#end
#if (Width != 0 & CenterX != 0)
#local ax = LDXSW/(Width / CenterX);
#end
#if (Height != 0 & CenterY != 0)
#local ay = LDXSW/(Height / CenterY);
#end
#if (Depth != 0 & CenterZ != 0)
#local az = LDXSW/(Depth / CenterZ);
#end
#if (aw <= 0)
#local aw = 1;
#local ax = 0;
#end
#if (ah <= 0)
#local ah = 1;
#local ay = 0;
#end
#if (ad <= 0)
#local ad = 1;
#local az = 0;
#end
matrix <aw,0,0,0,ah,0,0,0,ad,ax,ay,az>
#end


background { color rgb <LDXBgR,LDXBgG,LDXBgB> }

#declare lg_quality = LDXQual;
#if (lg_quality = 3)
#declare lg_quality = 4;
#end

#declare lg_studs = LDXStuds;


#include "lg_defs.inc"

#include "lg_color.inc"

#ifndef (LDXColor0) // Black
#declare LDXColor0 = #if (version >= 3.1) material { #end
	texture {
		lg_black
	}
#if (version >= 3.1) } #end
#declare LDXColor0_slope = #if (version >= 3.1) material { #end
	texture {
		lg_black
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor1) // Blue
#declare LDXColor1 = #if (version >= 3.1) material { #end
	texture {
		lg_blue
	}
#if (version >= 3.1) } #end
#declare LDXColor1_slope = #if (version >= 3.1) material { #end
	texture {
		lg_blue
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor4) // Red
#declare LDXColor4 = #if (version >= 3.1) material { #end
	texture {
		lg_red
	}
#if (version >= 3.1) } #end
#declare LDXColor4_slope = #if (version >= 3.1) material { #end
	texture {
		lg_red
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor7) // Light Gray
#declare LDXColor7 = #if (version >= 3.1) material { #end
	texture {
		lg_grey
	}
#if (version >= 3.1) } #end
#declare LDXColor7_slope = #if (version >= 3.1) material { #end
	texture {
		lg_grey
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor14) // Yellow
#declare LDXColor14 = #if (version >= 3.1) material { #end
	texture {
		lg_yellow
	}
#if (version >= 3.1) } #end
#declare LDXColor14_slope = #if (version >= 3.1) material { #end
	texture {
		lg_yellow
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor15) // White
#declare LDXColor15 = #if (version >= 3.1) material { #end
	texture {
		lg_white
	}
#if (version >= 3.1) } #end
#declare LDXColor15_slope = #if (version >= 3.1) material { #end
	texture {
		lg_white
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
#if (version >= 3.1) } #end
#end

#ifndef (LDXColor47) // Trans Clear
#declare LDXColor47 = #if (version >= 3.1) material { #end
	texture {
		lg_clear
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#declare LDXColor47_slope = #if (version >= 3.1) material { #end
	texture {
		lg_clear
		#if (LDXQual > 1) normal { bumps 0.3 scale 25*0.02 } #end
	}
	#if (LDXQual > 1) interior { lg_ior } #end
#if (version >= 3.1) } #end
#end

#include "lg_3149e.inc" // Hinge Plate  2 x  5 Base with Large Hole

#include "lg_2432.inc" // Tile  1 x  2 with Handle

#include "lg_stud4.inc" // Stud Tube Open

#declare LDX_1_dash_8cyli_dot_dat_in_part = cylinder // Cylinder 0.125
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-0.70710678118654746,0,0.70710678118654757>,0
		}
	}
}

#declare LDX_1_dash_8cyli_dot_dat = cylinder // Cylinder 0.125
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-0.70710678118654746,0,0.70710678118654757>,0
		}
	}
}

#declare LDX_1_dash_8cylo_dot_dat_in_part = union {
// Cylinder Open 0.125
// Name: 1-8cylo.dat
// Author: Tim Gould [timgould]
// !LDRAW_ORG Primitive UPDATE 2012-03
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2012-12-28 [PTadmin] Official Update 2012-03
	object {
		LDX_1_dash_8cyli_dot_dat_in_part
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
	}
}

#declare LDX_1_dash_8ndis_dot_dat_in_part = disc // Not-Disc 0.125
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-0.70710678118654746,0,0.70710678118654757>,0
		}
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_1_dash_8ndis_dot_dat = disc // Not-Disc 0.125
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-0.70710678118654746,0,0.70710678118654757>,0
		}
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_2_dash_4cyli_dot_dat_in_part = cylinder // Cylinder 0.5
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
	}
}

#declare LDX_2_dash_4cyli_dot_dat = cylinder // Cylinder 0.5
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
	}
}

#declare LDX_2_dash_4cylo_dot_dat_in_part = union {
// Cylinder Open 0.5
// Name: 2-4cylo.dat
// Author: Max Martin Richter [MMR1988]
// !LDRAW_ORG Primitive UPDATE 2010-03
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2010-12-31 [PTadmin] Official Update 2010-03
	object {
		LDX_2_dash_4cyli_dot_dat_in_part
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
	}
}

#declare LDX_2_dash_4ndis_dot_dat_in_part = disc // Not-Disc 0.5
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_2_dash_4ndis_dot_dat = disc // Not-Disc 0.5
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_s_slash_30350s01_dot_dat_in_part = union {
// ~Tile  2 x  3 with Horizontal Clips without Top
// Name: s\30350s01.dat
// Author: Paul Easter [pneaster]
// !LDRAW_ORG Subpart UPDATE 2012-03
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2001-11-23 [pneaster] corrected BFC use of primitive files.
// !HISTORY 2002-06-11 [PTadmin] Official Update 2002-03
// !HISTORY 2007-08-30 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2012-10-02 [Steffen] BFC rationalisation
// !HISTORY 2012-10-28 [MagFors] Removed overlapping surfaces, "boxified"
// !HISTORY 2012-12-28 [PTadmin] Official Update 2012-03
	#if (LDXStuds)
		object {
			lg_stud4
			matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		matrix <0,0,1,0,-1,0,-1,0,0,0,4,-10>
		}
		object {
			lg_stud4
			matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		matrix <0,0,1,0,-1,0,-1,0,0,0,4,10>
		}
	#end // LDXStuds
// BFC INVERTNEXT
// // top surface (used for patterning)
// // 4 16 -20 0 30 -20 0 -30 20 0 -30 20 0 30
// // clip
// BFC INVERTNEXT
	object {
		LDX_1_dash_8cylo_dot_dat_in_part
		matrix <0,-4,0,8,0,0,0,0,4,-14,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,-4,0,1,0,0,0,0,4,-14,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,-4,0,-1,0,0,0,0,4,-6,2,40>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4cylo_dot_dat_in_part
		matrix <0,4,0,8,0,0,0,0,-4,-14,2,40>
	}
	object {
		LDX_2_dash_4ndis_dot_dat_in_part
		matrix <0,-4,0,1,0,0,0,0,-4,-14,2,40>
	}
	object {
		LDX_2_dash_4ndis_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,-4,-6,2,40>
	}
// BFC INVERTNEXT
	object {
		LDX_1_dash_8cylo_dot_dat_in_part
		matrix <0,4,0,-8,0,0,0,0,4,-6,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,4,0,1,0,0,0,0,4,-14,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,4,-6,2,40>
	}
// // clip
// BFC INVERTNEXT
	object {
		LDX_1_dash_8cylo_dot_dat_in_part
		matrix <0,-4,0,8,0,0,0,0,4,6,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,-4,0,1,0,0,0,0,4,6,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,-4,0,-1,0,0,0,0,4,14,2,40>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4cylo_dot_dat_in_part
		matrix <0,4,0,8,0,0,0,0,-4,6,2,40>
	}
	object {
		LDX_2_dash_4ndis_dot_dat_in_part
		matrix <0,-4,0,1,0,0,0,0,-4,6,2,40>
	}
	object {
		LDX_2_dash_4ndis_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,-4,14,2,40>
	}
// BFC INVERTNEXT
	object {
		LDX_1_dash_8cylo_dot_dat_in_part
		matrix <0,4,0,-8,0,0,0,0,4,14,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,4,0,1,0,0,0,0,4,6,2,40>
	}
	object {
		LDX_1_dash_8ndis_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,4,14,2,40>
	}
}

#declare LDX_30350p01_dot_dat =
#if (LDXQual = 0)
box {
	<-20,-6,-30>,<20,10,46>
}
#else
union {
// Tile  2 x  3 with Horizontal Clips with Danger Chevron Pattern
// Name: 30350p01.dat
// Author: Ronald Scott Moody [rmoody]
// !LDRAW_ORG Part UPDATE 2004-04
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !KEYWORDS flag, mudflap
// !HISTORY 2003-07-05 [Steffen] re-worked part to make use of s\30350s01.dat, fixed part origin, polished part name, BFCed, removed bowtie quads
// !HISTORY 2004-11-06 [PTadmin] Official Update 2004-04
// !HISTORY 2007-06-07 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	object {
		LDX_s_slash_30350s01_dot_dat_in_part
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
	}
	mesh2 {
		vertex_vectors {
			31,
			<-15,0,-25>, <-15,0,-21>, <-15,0,-13>, <-15,0,-5>,
			<-15,0,3>, <-15,0,11>, <-15,0,19>, <-15,0,26>,
			<-11,0,-25>, <-8,0,26>, <-4,0,-10>, <-3,0,-25>,
			<0,0,-22>, <0,0,-14>, <0,0,-6>, <0,0,2>,
			<0,0,10>, <0,0,18>, <0,0,26>, <3,0,-25>,
			<4,0,-10>, <8,0,26>, <11,0,-25>, <15,0,-25>,
			<15,0,-21>, <15,0,-13>, <15,0,-5>, <15,0,3>,
			<15,0,11>, <15,0,19>, <15,0,26>
		}
		normal_vectors {
			1,
			<0,1,0>
		}
		face_indices {
			19,
			<12, 11, 19>, <1, 0, 8>, <10, 13, 20>, <10, 20, 14>,
			<22, 23, 24>, <7, 6, 9>, <29, 30, 21>, <1, 8, 13>,
			<1, 13, 10>, <22, 24, 20>, <22, 20, 13>, <3, 2, 15>,
			<3, 15, 16>, <16, 15, 25>, <16, 25, 26>, <5, 4, 17>,
			<5, 17, 18>, <18, 17, 27>, <18, 27, 28>
		}
		normal_indices {
			19,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>
		}
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	mesh2 {
		vertex_vectors {
			109,
			<-20,0,-30>, <-20,0,-25>, <-20,0,26>, <-20,0,30>,
			<-20,8,-30>, <-20,8,30>, <-16,4,-26>, <-16,4,26>,
			<-16,8,-26>, <-16,8,26>, <-15,0,-25>, <-15,0,-21>,
			<-15,0,-13>, <-15,0,-5>, <-15,0,3>, <-15,0,11>,
			<-15,0,19>, <-15,0,26>, <-14,-6,36>, <-14,-5,46>,
			<-14,-2,36>, <-14,-2,44>, <-14,-1,46>, <-14,-0.8284,42.8284>,
			<-14,0,30>, <-14,0,32>, <-14,4.8284,42.8284>, <-14,5,46>,
			<-14,6,36>, <-14,6,44>, <-14,8,30>, <-14,9,46>,
			<-14,10,34>, <-11,0,-25>, <-8,0,26>, <-6,-6,36>,
			<-6,-5,46>, <-6,-2,36>, <-6,-2,44>, <-6,-1,46>,
			<-6,-0.8284,42.8284>, <-6,0,30>, <-6,0,32>, <-6,4.8284,42.8284>,
			<-6,5,46>, <-6,6,36>, <-6,6,44>, <-6,8,30>,
			<-6,9,46>, <-6,10,34>, <-3,0,-25>, <0,0,-22>,
			<0,0,-14>, <0,0,-6>, <0,0,2>, <0,0,10>,
			<0,0,18>, <0,0,26>, <3,0,-25>, <6,-6,36>,
			<6,-5,46>, <6,-2,36>, <6,-2,44>, <6,-1,46>,
			<6,-0.8284,42.8284>, <6,0,30>, <6,0,32>, <6,4.8284,42.8284>,
			<6,5,46>, <6,6,36>, <6,6,44>, <6,8,30>,
			<6,9,46>, <6,10,34>, <8,0,26>, <11,0,-25>,
			<14,-6,36>, <14,-5,46>, <14,-2,36>, <14,-2,44>,
			<14,-1,46>, <14,-0.8284,42.8284>, <14,0,30>, <14,0,32>,
			<14,4.8284,42.8284>, <14,5,46>, <14,6,36>, <14,6,44>,
			<14,8,30>, <14,9,46>, <14,10,34>, <15,0,-25>,
			<15,0,-21>, <15,0,-13>, <15,0,-5>, <15,0,3>,
			<15,0,11>, <15,0,19>, <15,0,26>, <16,4,-26>,
			<16,4,26>, <16,8,-26>, <16,8,26>, <20,0,-30>,
			<20,0,-25>, <20,0,26>, <20,0,30>, <20,8,-30>,
			<20,8,30>
		}
		normal_vectors {
			12,
			<-1,0,0>, <0,-1,0>, <0,-0.99854,0.054026>, <0,-0.996546,-0.083045>,
			<0,-0.894427,0.447214>, <0,0,-1>, <0,0,1>, <0,0.5547,0.83205>,
			<0,0.995037,-0.099504>, <0,0.99854,0.054026>, <0,1,0>, <1,0,0>
		}
		face_indices {
			138,
			<6, 7, 100>, <6, 100, 99>, <6, 8, 9>, <6, 9, 7>,
			<99, 101, 8>, <99, 8, 6>, <100, 102, 101>, <100, 101, 99>,
			<7, 9, 102>, <7, 102, 100>, <4, 5, 9>, <4, 9, 8>,
			<108, 107, 101>, <108, 101, 102>, <108, 102, 9>, <108, 9, 5>,
			<101, 107, 4>, <101, 4, 8>, <107, 4, 0>, <107, 0, 103>,
			<4, 5, 3>, <4, 3, 0>, <103, 106, 108>, <103, 108, 107>,
			<24, 3, 5>, <24, 5, 30>, <65, 41, 47>, <65, 47, 71>,
			<106, 82, 88>, <106, 88, 108>, <42, 25, 24>, <42, 24, 41>,
			<35, 36, 19>, <35, 19, 18>, <35, 18, 25>, <35, 25, 42>,
			<39, 36, 19>, <39, 19, 22>, <39, 22, 23>, <39, 23, 40>,
			<27, 31, 48>, <27, 48, 44>, <27, 44, 43>, <27, 43, 26>,
			<32, 31, 48>, <32, 48, 49>, <32, 49, 47>, <32, 47, 30>,
			<21, 22, 23>, <19, 22, 21>, <18, 19, 21>, <18, 21, 20>,
			<30, 24, 25>, <30, 25, 32>, <32, 25, 18>, <32, 18, 28>,
			<32, 28, 29>, <32, 29, 31>, <27, 31, 29>, <27, 29, 26>,
			<40, 39, 38>, <38, 39, 36>, <37, 38, 36>, <37, 36, 35>,
			<49, 42, 41>, <49, 41, 47>, <45, 35, 42>, <45, 42, 49>,
			<48, 46, 45>, <48, 45, 49>, <46, 48, 44>, <43, 46, 44>,
			<83, 66, 65>, <83, 65, 82>, <76, 77, 60>, <76, 60, 59>,
			<76, 59, 66>, <76, 66, 83>, <80, 77, 60>, <80, 60, 63>,
			<80, 63, 64>, <80, 64, 81>, <68, 72, 89>, <68, 89, 85>,
			<68, 85, 84>, <68, 84, 67>, <73, 72, 89>, <73, 89, 90>,
			<73, 90, 88>, <73, 88, 71>, <62, 63, 64>, <60, 63, 62>,
			<59, 60, 62>, <59, 62, 61>, <71, 65, 66>, <71, 66, 73>,
			<73, 66, 59>, <73, 59, 69>, <73, 69, 70>, <73, 70, 72>,
			<68, 72, 70>, <68, 70, 67>, <81, 80, 79>, <79, 80, 77>,
			<78, 79, 77>, <78, 77, 76>, <90, 83, 82>, <90, 82, 88>,
			<86, 76, 83>, <86, 83, 90>, <89, 87, 86>, <89, 86, 90>,
			<87, 89, 85>, <84, 87, 85>, <2, 105, 106>, <2, 106, 3>,
			<0, 103, 104>, <0, 104, 1>, <1, 10, 17>, <1, 17, 2>,
			<91, 104, 105>, <91, 105, 98>, <16, 15, 57>, <16, 57, 34>,
			<96, 97, 74>, <96, 74, 57>, <14, 13, 55>, <14, 55, 56>,
			<56, 55, 94>, <56, 94, 95>, <12, 11, 53>, <12, 53, 54>,
			<54, 53, 92>, <54, 92, 93>, <50, 51, 52>, <50, 52, 33>,
			<52, 51, 58>, <52, 58, 75>
		}
		normal_indices {
			138,
			<1, 1, 1>, <1, 1, 1>, <0, 0, 0>, <0, 0, 0>,
			<5, 5, 5>, <5, 5, 5>, <11, 11, 11>, <11, 11, 11>,
			<6, 6, 6>, <6, 6, 6>, <1, 1, 1>, <1, 1, 1>,
			<1, 1, 1>, <1, 1, 1>, <1, 1, 1>, <1, 1, 1>,
			<1, 1, 1>, <1, 1, 1>, <5, 5, 5>, <5, 5, 5>,
			<0, 0, 0>, <0, 0, 0>, <11, 11, 11>, <11, 11, 11>,
			<6, 6, 6>, <6, 6, 6>, <6, 6, 6>, <6, 6, 6>,
			<6, 6, 6>, <6, 6, 6>, <10, 10, 10>, <10, 10, 10>,
			<8, 8, 8>, <8, 8, 8>, <7, 7, 7>, <7, 7, 7>,
			<6, 6, 6>, <6, 6, 6>, <9, 9, 9>, <9, 9, 9>,
			<6, 6, 6>, <6, 6, 6>, <2, 2, 2>, <2, 2, 2>,
			<3, 3, 3>, <3, 3, 3>, <4, 4, 4>, <4, 4, 4>,
			<11, 11, 11>, <11, 11, 11>, <11, 11, 11>, <11, 11, 11>,
			<11, 11, 11>, <11, 11, 11>, <11, 11, 11>, <11, 11, 11>,
			<11, 11, 11>, <11, 11, 11>, <11, 11, 11>, <11, 11, 11>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<10, 10, 10>, <10, 10, 10>, <8, 8, 8>, <8, 8, 8>,
			<7, 7, 7>, <7, 7, 7>, <6, 6, 6>, <6, 6, 6>,
			<9, 9, 9>, <9, 9, 9>, <6, 6, 6>, <6, 6, 6>,
			<2, 2, 2>, <2, 2, 2>, <3, 3, 3>, <3, 3, 3>,
			<4, 4, 4>, <4, 4, 4>, <11, 11, 11>, <11, 11, 11>,
			<11, 11, 11>, <11, 11, 11>, <11, 11, 11>, <11, 11, 11>,
			<11, 11, 11>, <11, 11, 11>, <11, 11, 11>, <11, 11, 11>,
			<11, 11, 11>, <11, 11, 11>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>, <10, 10, 10>, <10, 10, 10>,
			<10, 10, 10>, <10, 10, 10>
		}
	}
}
#end

#include "lg_3956.inc" // Bracket  2 x  2 -  2 x  2 Up

#include "lg_3660.inc" // Slope Brick 45  2 x  2 Inverted

#include "lg_0313.inc" // ~Hinge Plate  2 x  5 Pivot

#include "lg_3679.inc" // Turntable  2 x  2 Plate Top

#include "lg_3700.inc" // Technic Brick  1 x  2 with Hole

#include "lg_3680.inc" // Turntable  2 x  2 Plate Base

#include "lg_3023.inc" // Plate  1 x  2

#declare LDX_PELVIS_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3700
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,8,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3700
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,8,10>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,10,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
// 0 0 0 0 0 0 1 0 1 0 -1 0 0 axis_32s.dat
}

#declare LDX_WAIST_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3149e
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 16, 98, 0, 0, -41)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_2432
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 32, 20.000101, 0, 16, 0.000051)
		matrix <-1,0,0,0,1,0,0,0,-1,10,-34,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_30350p01_dot_dat
		LDXSeamMatrix(40, 16, 76, 0, 2, 8)
		matrix <-1,0,0,0,1,0,0,0,-1,10,-10,-60>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3956
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 48, 52, 0, -16, -6)
		matrix <1,0,0,0,0,-1,0,1,0,10,34,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3660
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,10,14,-40>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3660_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,10,14,-40>
		#if (version >= 3.1) material #else texture #end { LDXColor1_slope }
	}
	object {
		lg_0313
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(32, 12, 12, 0, 0, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor4 }
	}
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <-1,0,0,0,0,-1,0,-1,0,10,34,-58>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		LDX_PELVIS_dot_DAT
		matrix <0,1,0,0,0,-1,-1,0,0,10,34,-58>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#include "lg_3816.inc" // Minifig Leg Right

#include "lg_3817.inc" // Minifig Leg Left

#include "lg_0973p68.inc" // Minifig Torso with MTron Logo Pattern

#include "lg_3626bp01.inc" // Minifig Head with Standard Grin Pattern

#include "lg_2446.inc" // Minifig Helmet Modern

#include "lg_2447.inc" // Minifig Helmet Visor

#include "lg_3815.inc" // Minifig Hips

#include "lg_0976.INC" // ~Minifig Arm Left (Obsolete)

#include "lg_0977.INC" // ~Minifig Hand (Obsolete)

#declare LDX_LIMBL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_0976
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(12.484699, 29.181366, 18.261364, 20.604, 8.848385, -3.819385)
		matrix <1,0,0,0,0.71,-0.71,0,0.71,0.71,-30,-4,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_0977
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(25.52, 12, 12, 3.24, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-8,-1,-29>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#include "lg_0975.INC" // ~Minifig Arm Right (Obsolete)

#declare LDX_LIMBR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_0975
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(12.484699, 29.181366, 18.261364, -20.604, 8.848385, -3.819385)
		matrix <1,0,0,0,0.71,-0.71,0,0.71,0.71,20,-4,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_0977
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(25.52, 12, 12, 3.24, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-2,-1,-29>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_PILOT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_0973p68
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(38, 44, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3626bp01
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(26, 28, 26, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor14 }
	}
	object {
		lg_2446
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(31.6, 34.615421, 34.5, 0, 7.807711, -1.25)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2447_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(34, 17, 24, 0, 11, -8)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
	object {
		lg_3815
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(36, 32.000195, 20, 0, 5.000097, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_LIMBL_dot_DAT
		matrix <1,0,0,0,0.91,0.42,0,-0.42,0.91,40,12.78,1.49>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_LIMBR_dot_DAT
		matrix <1,0,0,0,0.91,0.42,0,-0.42,0.91,-10,12.78,1.49>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_1_dash_8sphe_dot_dat_in_part = sphere // Sphere .125
{
	<0,0,0>,1
	clipped_by
	{
		box
		{
			<0,0,0>,<2,2,2>
		}
	}
}

#declare LDX_1_dash_8sphe_dot_dat = sphere // Sphere .125
{
	<0,0,0>,1
	clipped_by
	{
		box
		{
			<0,0,0>,<2,2,2>
		}
	}
}

#declare LDX_4_dash_8SPHE_dot_DAT_in_part = union {
// Sphere 0.5
// Name: 4-8sphe.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2003-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-08-31 [izanette] Modified with WINDZ for BFC compliance
// !HISTORY 2003-08-01 [PTadmin] Official Update 2003-02
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	object {
		LDX_1_dash_8sphe_dot_dat_in_part
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
	}
	object {
		LDX_1_dash_8sphe_dot_dat_in_part
		matrix <1,0,0,0,1,0,0,0,-1,0,0,0>
	}
	object {
		LDX_1_dash_8sphe_dot_dat_in_part
		matrix <-1,0,0,0,1,0,0,0,1,0,0,0>
	}
	object {
		LDX_1_dash_8sphe_dot_dat_in_part
		matrix <-1,0,0,0,1,0,0,0,-1,0,0,0>
	}
}

#declare LDX_1_dash_4disc_dot_dat_in_part = disc // Disc 0.25
{
	<0,0,0>,<0,1,0>,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-1,0,0>,0
		}
	}
}

#declare LDX_1_dash_4disc_dot_dat = disc // Disc 0.25
{
	<0,0,0>,<0,1,0>,1
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-1,0,0>,0
		}
	}
}

#declare LDX_1_dash_4cyli_dot_dat_in_part = cylinder // Cylinder 0.25
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-1,0,0>,0
		}
	}
}

#declare LDX_1_dash_4cyli_dot_dat = cylinder // Cylinder 0.25
{
	<0,0,0>,<0,1,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<-1,0,0>,0
		}
	}
}

#declare LDX_4_dash_4ring3_dot_dat_in_part = disc // Ring 1
{
	<0,0,0>,<0,1,0>,4,3
}

#declare LDX_4_dash_4ring3_dot_dat = disc // Ring 1
{
	<0,0,0>,<0,1,0>,4,3
}

#declare LDX_4_dash_4cyli_dot_dat_in_part = cylinder // Cylinder 1
{
	<0,0,0>,<0,1,0>,1 open
}

#declare LDX_4_dash_4cyli_dot_dat = cylinder // Cylinder 1
{
	<0,0,0>,<0,1,0>,1 open
}

#declare LDX_peghole_dot_dat_in_part = union {
// Peg Hole End
// Name: peghole.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2010-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2002-05-01 [mkennedy] replace code with ring3
// !HISTORY 2002-05-01 [sbliss] BFC
// !HISTORY 2002-06-11 [PTadmin] Official Update 2002-03
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2010-01-14 [cwdee] Update ring3 to 4-4ring3
// !HISTORY 2010-04-05 [PTadmin] Official Update 2010-01
	object {
		LDX_4_dash_4ring3_dot_dat_in_part
		matrix <2,0,0,0,1,0,0,0,2,0,2,0>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <8,0,0,0,2,0,0,0,8,0,0,0>
	}
}

#declare LDX_4_dash_4ndis_dot_dat_in_part = disc // Not-Disc 1
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_4_dash_4ndis_dot_dat = disc // Not-Disc 1
{
	<0,0,0>,<0,1,0>,2,1
	clipped_by
	{
		box
		{
			<-1,-1,-1>,<1,1,1>
		}
	}
}

#declare LDX_2_dash_4CYLS_dot_DAT_in_part = cylinder // Sloped Cylinder 0.5
{
	<0,0,0>,<0,2,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<1,1,0>,0.70710678118654757
		}
	}
}

#declare LDX_2_dash_4cyls_dot_dat = cylinder // Sloped Cylinder 0.5
{
	<0,0,0>,<0,2,0>,1 open
	clipped_by
	{
		plane
		{
			<0,0,-1>,0
		}
		plane
		{
			<1,1,0>,0.70710678118654757
		}
	}
}

#declare LDX_stud4a_dot_dat_in_part = union {
// Stud Tube Open without Base Edges
// Name: stud4a.dat
// Author: James Jessiman
// !LDRAW_ORG Primitive UPDATE 2009-02
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 1999-07-05 [PTadmin] Official Update 1999-05
// !HISTORY 2002-04-04 [sbliss] Modified for BFC compliance
// !HISTORY 2002-04-25 [PTadmin] Official Update 2002-02
// !HISTORY 2007-06-24 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// !HISTORY 2009-06-21 [cwdee] Update ring references to 4-4ring
// !HISTORY 2009-09-03 [PTadmin] Official Update 2009-02
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <6,0,0,0,4,0,0,0,6,0,-4,0>
	}
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <8,0,0,0,4,0,0,0,8,0,-4,0>
	}
	object {
		LDX_4_dash_4ring3_dot_dat_in_part
		matrix <2,0,0,0,1,0,0,0,2,0,-4,0>
	}
}

#declare LDX_2717_dot_dat =
#if (LDXQual = 0)
box {
	<-40,-80,-30>,<40,0,37>
}
#else
union {
// Technic Seat  3 x  2 Base
// Name: 2717.dat
// Author: Tore Eriksson [Tore_Eriksson]
// !LDRAW_ORG Part UPDATE 2005-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2000-05-07 [PTadmin] Official Update 2000-01
// !HISTORY 2004-07-30 [guyvivan] Add Missing lines, quads and optional lines
// !HISTORY 2005-12-28 [PTadmin] Official Update 2005-01
// !HISTORY 2007-05-18 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
	object {
		LDX_4_dash_8SPHE_dot_DAT_in_part
		matrix <0,2,0,1,0,0,0,0,2,-20,-41.5,13>
	}
	object {
		LDX_4_dash_8SPHE_dot_DAT_in_part
		matrix <0,2,0,-1,0,0,0,0,2,20,-41.5,13>
	}
	#if (LDXStuds)
		object {
			lg_stud4
			matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		matrix <1,0,0,0,-1,0,0,0,1,0,-4,10>
		}
		object {
			lg_stud4
			matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		matrix <1,0,0,0,-1,0,0,0,1,0,-4,-10>
		}
	#end // LDXStuds
// BFC INVERTNEXT
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <3,0,0,0,0,1,0,3,0,27,-8,-30>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <-3,0,0,0,0,1,0,3,0,-27,-8,-30>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <3,0,0,0,0,-1,0,3,-0.75,20,-8,19>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <-3,0,0,0,0,-1,0,3,-0.75,-20,-8,19>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <3,0,0,-7,0,48.25,0,3,0,27,-8,-30>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <-3,0,0,7,0,48.25,0,3,0,-27,-8,-30>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <3,0,0,0,0,-0.75,0,3,-0.75,20,-8,19>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <-3,0,0,0,0,-0.75,0,3,-0.75,-20,-8,19>
	}
// SIMPLIFY: Filling cavities below armrest
// /SIMPLIFY: Filling cavities below armrest
	object {
		LDX_peghole_dot_dat_in_part
		matrix <0,1,0,-1,0,0,0,0,1,40,-22,-10>
	}
	object {
		LDX_peghole_dot_dat_in_part
		matrix <0,1,0,1,0,0,0,0,1,-40,-22,-10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,8,0,-1,0,0,0,0,8,40,-22,-10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,8,0,1,0,0,0,0,8,-40,-22,-10>
	}
	object {
		LDX_peghole_dot_dat_in_part
		matrix <0,1,0,-1,0,0,0,0,1,40,-22,10>
	}
	object {
		LDX_peghole_dot_dat_in_part
		matrix <0,1,0,1,0,0,0,0,1,-40,-22,10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,8,0,-1,0,0,0,0,8,40,-22,10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,8,0,1,0,0,0,0,8,-40,-22,10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,6,0,1,0,0,0,0,6,24,-22,10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,6,0,-1,0,0,0,0,6,-24,-22,10>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <0,6,0,14,0,0,0,0,6,24,-22,10>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <0,6,0,-14,0,0,0,0,6,-24,-22,10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,6,0,1,0,0,-0.6,0,6,25,-22,-10>
	}
	object {
		LDX_4_dash_4ndis_dot_dat_in_part
		matrix <0,6,0,-1,0,0,0.6,0,6,-25,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <0,6,0,12.4,0,0,0,0,6,25.6,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <0,6,0,-12.4,0,0,0,0,6,-25.6,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,0,-6,-0.6,0,0,0,6,0,25.6,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,0,-6,0.6,0,0,0,6,0,-25.6,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,0,-6,-0.6,0,0,0,-6,0,25.6,-22,-10>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,0,-6,0.6,0,0,0,-6,0,-25.6,-22,-10>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <0,4,0,4,0,0,0,0,-4,20,-42,13.5>
	}
	object {
		LDX_1_dash_4cyli_dot_dat_in_part
		matrix <0,4,0,-4,0,0,0,0,-4,-20,-42,13.5>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <0,4,0,1,0,0,0,0,-4,20,-42,13.5>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,-4,-20,-42,13.5>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <0,4,0,-1,0,0,0,0,-4,24,-42,13.5>
	}
	object {
		LDX_1_dash_4disc_dot_dat_in_part
		matrix <0,4,0,1,0,0,0,0,-4,-24,-42,13.5>
	}
	#if (LDXStuds)
		object {
			LDX_stud4a_dot_dat_in_part
			matrix <1,0,0,0,0,-1.125,0,1,0,0,-28,25.5>
		}
	#end // LDXStuds
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,-8,0,0,0,-2,8,0,0,0,-28,25.5>
	}
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,-8,0,0,0,-2,-8,0,0,0,-28,25.5>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,-6,0,0,0,-1.5,6,0,0,0,-28,25>
	}
// BFC INVERTNEXT
	object {
		LDX_2_dash_4CYLS_dot_DAT_in_part
		matrix <0,-6,0,0,0,-1.5,-6,0,0,0,-28,25>
	}
// BFC INVERTNEXT
	object {
		LDX_4_dash_4cyli_dot_dat_in_part
		matrix <6,0,0,0,0,-0.5,0,6,0,0,-28,25.5>
	}
	mesh2 {
		vertex_vectors {
			224,
			<-40,-32,-20>, <-40,-32,0>, <-40,-32,25>, <-40,-31.695999,-21.531>,
			<-40,-30.827999,-22.827999>, <-40,-30,-18>, <-40,-30,-2>, <-40,-30,2>,
			<-40,-30,18>, <-40,-29.531,-23.695999>, <-40,-28,-20>, <-40,-14,-18>,
			<-40,-14,-2>, <-40,-14,2>, <-40,-14,18>, <-40,-12,-30>,
			<-40,-12,20>, <-36,-28,19>, <-36,-28,24>, <-36,-12,19>,
			<-36,-12,20>, <-30,-12,-30>, <-30,-8,-30>, <-27,-12,-30>,
			<-27,-8,-30>, <-27,-5,-30>, <-26.25,-29.531,-23.695999>, <-26.25,-29.531,-23.691>,
			<-26.120001,-30.827999,-22.827999>, <-26.030001,-31.695999,-21.531>, <-26,-32,-20>, <-26,-8,-20>,
			<-25.6,-28,-16>, <-25.6,-16,-16>, <-24.4,-28,-4>, <-24.4,-16,-4>,
			<-24,-80,32>, <-24,-80,37>, <-24,-70,29.5>, <-24,-48,29>,
			<-24,-43.25,10>, <-24,-42,9.5>, <-24,-42,13.5>, <-24,-38,13.5>,
			<-24,-38,21.5>, <-24,-32,0>, <-24,-32,20>, <-24,-32,25>,
			<-24,-28,4>, <-24,-28,16>, <-24,-28,19>, <-24,-28,24>,
			<-24,-17,16.25>, <-24,-16,4>, <-24,-16,16>, <-24,-15.75,15.543>,
			<-24,-14.7,14.243>, <-24,-14.1,12.296>, <-24,-14,0>, <-24,-14,10>,
			<-24,-14,16>, <-24,-12,19>, <-24,-12,20>, <-24,-8,0>,
			<-23.4,-8,6>, <-23.017,-8.761,9.827>, <-23,-14,10>, <-23,-12,19>,
			<-23,-12,20>, <-23,-8,19>, <-22.77,-14.1,12.296>, <-22.693001,-10.929,13.071>,
			<-22.576,-14.7,14.243>, <-22.476,-14.173,15.239>, <-22.445999,-15.75,15.543>, <-22.375,-17,16.25>,
			<-20,-70,29.5>, <-20,-48,29>, <-20,-48,30>, <-20,-43.25,10>,
			<-20,-42,9.5>, <-20,-42,13.5>, <-20,-38,13.5>, <-20,-38,21.5>,
			<-20,-12,20>, <-20,-8,19>, <-20,-5,-30>, <-20,-5,18.25>,
			<-20,0,-30>, <-20,0,30>, <-16,-76,34>, <-16,-76,36>,
			<-16,-48,27>, <-16,-48,29>, <-16,-44,26>, <-16,-44,30>,
			<-16,-38,26>, <-16,-38,30>, <-16,-8,18.5>, <-16,-8,30>,
			<-16,-4,-26>, <-16,-4,26>, <-16,0,-26>, <-16,0,26>,
			<-11,-12,19.5>, <-11,-12,30>, <-11,-8,18.5>, <-11,-8,30>,
			<-8,-12,19.5>, <-8,-12,30>, <-8,-8,18.5>, <-8,-8,30>,
			<8,-12,19.5>, <8,-12,30>, <8,-8,18.5>, <8,-8,30>,
			<11,-12,19.5>, <11,-12,30>, <11,-8,18.5>, <11,-8,30>,
			<16,-76,34>, <16,-76,36>, <16,-48,27>, <16,-48,29>,
			<16,-44,26>, <16,-44,30>, <16,-38,26>, <16,-38,30>,
			<16,-8,18.5>, <16,-8,30>, <16,-4,-26>, <16,-4,26>,
			<16,0,-26>, <16,0,26>, <20,-70,29.5>, <20,-48,29>,
			<20,-48,30>, <20,-43.25,10>, <20,-42,9.5>, <20,-42,13.5>,
			<20,-38,13.5>, <20,-38,21.5>, <20,-12,20>, <20,-8,19>,
			<20,-5,-30>, <20,-5,18.25>, <20,0,-30>, <20,0,30>,
			<22.375,-17,16.25>, <22.445999,-15.75,15.543>, <22.476,-14.173,15.239>, <22.576,-14.7,14.243>,
			<22.693001,-10.929,13.071>, <22.77,-14.1,12.296>, <23,-14,10>, <23,-12,19>,
			<23,-12,20>, <23,-8,19>, <23.017,-8.761,9.827>, <23.4,-8,6>,
			<24,-80,32>, <24,-80,37>, <24,-70,29.5>, <24,-48,29>,
			<24,-43.25,10>, <24,-42,9.5>, <24,-42,13.5>, <24,-38,13.5>,
			<24,-38,21.5>, <24,-32,0>, <24,-32,20>, <24,-32,25>,
			<24,-28,4>, <24,-28,16>, <24,-28,19>, <24,-28,24>,
			<24,-17,16.25>, <24,-16,4>, <24,-16,16>, <24,-15.75,15.543>,
			<24,-14.7,14.243>, <24,-14.1,12.296>, <24,-14,0>, <24,-14,10>,
			<24,-14,16>, <24,-12,19>, <24,-12,20>, <24,-8,0>,
			<24.4,-28,-4>, <24.4,-16,-4>, <25.6,-28,-16>, <25.6,-16,-16>,
			<26,-32,-20>, <26,-8,-20>, <26.030001,-31.695999,-21.531>, <26.120001,-30.827999,-22.827999>,
			<26.25,-29.531,-23.695999>, <26.25,-29.531,-23.691>, <27,-12,-30>, <27,-8,-30>,
			<27,-5,-30>, <30,-12,-30>, <30,-8,-30>, <36,-28,19>,
			<36,-28,24>, <36,-12,19>, <36,-12,20>, <40,-32,-20>,
			<40,-32,0>, <40,-32,25>, <40,-31.695999,-21.531>, <40,-30.827999,-22.827999>,
			<40,-30,-18>, <40,-30,-2>, <40,-30,2>, <40,-30,18>,
			<40,-29.531,-23.695999>, <40,-28,-20>, <40,-14,-18>, <40,-14,-2>,
			<40,-14,2>, <40,-14,18>, <40,-12,-30>, <40,-12,20>
		}
		normal_vectors {
			49,
			<-1,0,0>, <-0.999057,-0.001539,0.043396>, <-0.998223,0,0.059595>, <-0.996808,-0.003572,0.079755>,
			<-0.994974,-0.007143,0.099875>, <-0.994782,-0.005933,0.101851>, <-0.994915,-0.002967,0.100678>, <-0.995043,-0.000025,0.099451>,
			<-0.995037,0,0.099504>, <-0.994906,0.000505,0.100805>, <-0.991124,-0.0112,0.132466>, <-0.989747,-0.034641,-0.138565>,
			<-0.989998,-0.017323,-0.140014>, <-0.98995,0,-0.141421>, <0,-1,0>, <0,-0.242536,-0.970143>,
			<0,0,-1>, <0,0,1>, <0,0.242536,0.970143>, <0,0.338379,0.94101>,
			<0,0.359423,0.933175>, <0,0.371391,0.928477>, <0,0.37079,0.928717>, <0,0.44958,0.89324>,
			<0,0.450644,0.892703>, <0,0.483988,0.875075>, <0,0.589069,0.808082>, <0,0.646556,0.762866>,
			<0,0.707107,0.707107>, <0,0.882722,0.469896>, <0,0.923804,0.382866>, <0,0.985376,0.170394>,
			<0,0.995201,0.09785>, <0,1,0>, <0,0.999763,0.021762>, <0.989747,-0.034641,-0.138565>,
			<0.989998,-0.017323,-0.140014>, <0.98995,0,-0.141421>, <0.991124,-0.0112,0.132466>, <0.994974,-0.007143,0.099875>,
			<0.994782,-0.005933,0.101851>, <0.994915,-0.002967,0.100678>, <0.995049,-0.000048,0.099382>, <0.995037,0,0.099504>,
			<0.994906,0.000505,0.100805>, <0.996808,-0.003572,0.079755>, <0.998223,0,0.059595>, <0.999057,-0.001539,0.043396>,
			<1,0,0>
		}
		face_indices {
			326,
			<101, 131, 130>, <101, 130, 100>, <101, 103, 133>, <101, 133, 131>,
			<100, 102, 103>, <100, 103, 101>, <130, 132, 102>, <130, 102, 100>,
			<131, 133, 132>, <131, 132, 130>, <88, 102, 132>, <88, 132, 146>,
			<147, 133, 103>, <147, 103, 89>, <89, 103, 102>, <89, 102, 88>,
			<146, 132, 133>, <146, 133, 147>, <202, 201, 198>, <202, 198, 199>,
			<24, 23, 21>, <24, 21, 22>, <145, 200, 144>, <86, 25, 87>,
			<144, 146, 147>, <144, 147, 145>, <88, 86, 87>, <88, 87, 89>,
			<143, 145, 147>, <89, 87, 85>, <143, 147, 136>, <143, 136, 135>,
			<89, 85, 77>, <89, 77, 78>, <157, 143, 142>, <157, 142, 156>,
			<85, 69, 68>, <85, 68, 84>, <204, 203, 174>, <204, 174, 175>,
			<51, 50, 17>, <51, 17, 18>, <185, 186, 175>, <185, 175, 174>,
			<62, 61, 50>, <62, 50, 51>, <204, 206, 205>, <204, 205, 203>,
			<17, 19, 20>, <17, 20, 18>, <185, 174, 203>, <185, 203, 205>,
			<19, 17, 50>, <19, 50, 61>, <201, 202, 157>, <201, 157, 156>,
			<22, 21, 69>, <21, 68, 69>, <155, 205, 222>, <155, 222, 201>,
			<19, 67, 21>, <19, 21, 15>, <206, 223, 222>, <206, 222, 205>,
			<19, 15, 16>, <19, 16, 20>, <156, 186, 185>, <156, 185, 155>,
			<67, 61, 62>, <67, 62, 68>, <186, 142, 135>, <186, 135, 163>,
			<84, 62, 39>, <84, 39, 77>, <204, 175, 171>, <204, 171, 209>,
			<51, 18, 2>, <51, 2, 47>, <209, 223, 206>, <209, 206, 204>,
			<18, 20, 16>, <18, 16, 2>, <146, 144, 86>, <146, 86, 88>,
			<200, 199, 24>, <200, 24, 25>, <147, 129, 125>, <147, 125, 136>,
			<99, 89, 78>, <99, 78, 95>, <89, 99, 129>, <89, 129, 147>,
			<136, 125, 95>, <136, 95, 78>, <209, 207, 212>, <209, 212, 215>,
			<0, 2, 8>, <0, 8, 5>, <222, 223, 221>, <222, 221, 218>,
			<16, 15, 11>, <16, 11, 14>, <214, 213, 219>, <214, 219, 220>,
			<6, 7, 13>, <6, 13, 12>, <223, 209, 215>, <223, 215, 221>,
			<2, 16, 14>, <2, 14, 8>, <171, 169, 208>, <171, 208, 209>,
			<45, 47, 2>, <45, 2, 1>, <170, 173, 172>, <170, 172, 169>,
			<45, 48, 49>, <45, 49, 46>, <46, 49, 54>, <170, 178, 173>,
			<207, 217, 218>, <207, 218, 212>, <10, 0, 5>, <10, 5, 11>,
			<178, 184, 182>, <178, 182, 177>, <53, 58, 60>, <53, 60, 54>,
			<169, 192, 207>, <169, 207, 208>, <30, 45, 1>, <30, 1, 0>,
			<169, 172, 177>, <169, 177, 182>, <48, 45, 58>, <48, 58, 53>,
			<187, 189, 188>, <187, 188, 169>, <45, 34, 35>, <45, 35, 63>,
			<192, 190, 191>, <192, 191, 193>, <31, 33, 32>, <31, 32, 30>,
			<192, 169, 188>, <192, 188, 190>, <45, 30, 32>, <45, 32, 34>,
			<187, 193, 191>, <187, 191, 189>, <31, 63, 35>, <31, 35, 33>,
			<217, 207, 210>, <217, 210, 211>, <0, 10, 4>, <0, 4, 3>,
			<217, 211, 216>, <4, 10, 9>, <216, 222, 218>, <216, 218, 217>,
			<15, 9, 10>, <15, 10, 11>, <193, 198, 196>, <23, 31, 26>,
			<193, 199, 198>, <31, 23, 24>, <193, 195, 194>, <193, 197, 195>,
			<28, 31, 29>, <27, 31, 28>, <193, 194, 192>, <30, 29, 31>,
			<207, 192, 194>, <207, 194, 210>, <30, 0, 3>, <30, 3, 29>,
			<210, 194, 195>, <210, 195, 211>, <29, 3, 4>, <29, 4, 28>,
			<211, 195, 196>, <211, 196, 216>, <28, 4, 9>, <28, 9, 26>,
			<196, 198, 222>, <196, 222, 216>, <9, 15, 23>, <9, 23, 26>,
			<161, 163, 123>, <161, 123, 121>, <39, 37, 91>, <39, 91, 93>,
			<170, 171, 161>, <170, 161, 160>, <47, 46, 36>, <47, 36, 37>,
			<120, 121, 123>, <120, 123, 122>, <91, 90, 92>, <91, 92, 93>,
			<162, 134, 137>, <162, 137, 164>, <76, 38, 40>, <76, 40, 79>,
			<164, 137, 138>, <164, 138, 165>, <79, 40, 41>, <79, 41, 80>,
			<167, 140, 141>, <167, 141, 168>, <82, 43, 44>, <82, 44, 83>,
			<139, 137, 134>, <76, 79, 81>, <162, 164, 166>, <40, 38, 42>,
			<138, 137, 139>, <81, 79, 80>, <166, 164, 165>, <41, 40, 42>,
			<141, 140, 139>, <141, 139, 134>, <76, 81, 82>, <76, 82, 83>,
			<162, 166, 167>, <162, 167, 168>, <42, 38, 44>, <42, 44, 43>,
			<91, 37, 161>, <91, 161, 121>, <121, 120, 90>, <121, 90, 91>,
			<37, 36, 160>, <37, 160, 161>, <120, 122, 92>, <120, 92, 90>,
			<93, 92, 122>, <93, 122, 123>, <78, 77, 135>, <78, 135, 136>,
			<183, 154, 182>, <58, 66, 59>, <154, 183, 181>, <154, 181, 153>,
			<59, 66, 70>, <59, 70, 57>, <153, 181, 180>, <153, 180, 151>,
			<57, 70, 72>, <57, 72, 56>, <151, 180, 179>, <151, 179, 149>,
			<56, 72, 74>, <56, 74, 55>, <149, 179, 176>, <149, 176, 148>,
			<55, 74, 75>, <55, 75, 52>, <159, 154, 153>, <159, 153, 158>,
			<66, 64, 65>, <66, 65, 70>, <158, 153, 151>, <158, 151, 152>,
			<70, 65, 71>, <70, 71, 72>, <152, 151, 149>, <152, 149, 150>,
			<72, 71, 73>, <72, 73, 74>, <150, 149, 148>, <73, 75, 74>,
			<187, 182, 154>, <187, 154, 159>, <58, 63, 64>, <58, 64, 66>,
			<124, 126, 96>, <124, 96, 94>, <113, 115, 114>, <113, 114, 112>,
			<111, 109, 108>, <111, 108, 110>, <117, 113, 112>, <117, 112, 116>,
			<109, 105, 104>, <109, 104, 108>, <119, 117, 116>, <119, 116, 118>,
			<105, 107, 106>, <105, 106, 104>, <115, 113, 117>, <115, 117, 119>,
			<107, 105, 109>, <107, 109, 111>, <124, 125, 127>, <124, 127, 126>,
			<95, 94, 96>, <95, 96, 97>, <129, 128, 126>, <129, 126, 127>,
			<98, 99, 97>, <98, 97, 96>, <95, 125, 124>, <95, 124, 94>,
			<99, 98, 128>, <99, 128, 129>, <126, 128, 98>, <126, 98, 96>,
			<63, 24, 199>, <63, 199, 187>, <187, 159, 64>, <187, 64, 63>,
			<159, 158, 65>, <159, 65, 64>, <158, 152, 71>, <158, 71, 65>,
			<152, 150, 73>, <152, 73, 71>, <150, 148, 75>, <150, 75, 73>,
			<46, 75, 148>, <46, 148, 170>, <148, 176, 170>, <52, 75, 46>,
			<36, 46, 170>, <36, 170, 160>
		}
		normal_indices {
			326,
			<14, 14, 14>, <14, 14, 14>, <17, 17, 17>, <17, 17, 17>,
			<0, 0, 0>, <0, 0, 0>, <16, 16, 16>, <16, 16, 16>,
			<48, 48, 48>, <48, 48, 48>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <17, 17, 17>, <17, 17, 17>,
			<17, 17, 17>, <17, 17, 17>, <14, 14, 14>, <14, 14, 14>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <15, 15, 15>, <15, 15, 15>,
			<15, 15, 15>, <15, 15, 15>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <16, 16, 16>, <16, 16, 16>,
			<16, 16, 16>, <16, 16, 16>, <12, 13, 12>, <12, 12, 11>,
			<37, 36, 36>, <36, 35, 36>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <14, 14, 14>, <14, 14, 14>,
			<14, 14, 14>, <14, 14, 14>, <15, 15, 15>, <15, 15, 15>,
			<15, 15, 15>, <15, 15, 15>, <15, 15, 15>, <15, 15, 15>,
			<15, 15, 15>, <15, 15, 15>, <15, 15, 15>, <15, 15, 15>,
			<15, 15, 15>, <15, 15, 15>, <17, 17, 17>, <17, 17, 17>,
			<17, 17, 17>, <17, 17, 17>, <16, 16, 16>, <16, 16, 16>,
			<16, 16, 16>, <16, 16, 16>, <16, 16, 16>, <16, 16, 16>,
			<16, 16, 16>, <16, 16, 16>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <33, 33, 33>, <33, 33, 33>,
			<33, 33, 33>, <33, 33, 33>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <0, 0, 0>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<33, 32, 32>, <33, 32, 33>, <32, 33, 33>, <32, 33, 32>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<43, 43, 43>, <43, 43, 43>, <8, 8, 8>, <8, 8, 8>,
			<46, 43, 43>, <46, 43, 45>, <3, 8, 8>, <3, 8, 2>,
			<46, 43, 43>, <46, 43, 43>, <8, 2, 8>, <8, 8, 8>,
			<43, 45, 43>, <43, 43, 43>, <3, 8, 8>, <3, 8, 8>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <41, 41, 40>, <6, 6, 5>,
			<41, 43, 41>, <6, 6, 8>, <45, 39, 47>, <45, 38, 39>,
			<4, 3, 1>, <10, 3, 4>, <45, 47, 46>, <2, 1, 3>,
			<32, 32, 30>, <32, 30, 30>, <32, 32, 30>, <32, 30, 30>,
			<30, 30, 28>, <30, 28, 28>, <30, 30, 28>, <30, 28, 28>,
			<28, 28, 24>, <28, 24, 24>, <28, 28, 24>, <28, 24, 24>,
			<24, 19, 19>, <24, 19, 24>, <24, 19, 19>, <24, 19, 24>,
			<15, 15, 15>, <15, 15, 15>, <15, 15, 15>, <15, 15, 15>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<26, 26, 25>, <26, 25, 25>, <26, 26, 25>, <26, 25, 25>,
			<25, 25, 21>, <25, 21, 21>, <25, 25, 21>, <25, 21, 21>,
			<14, 14, 14>, <14, 14, 14>, <14, 14, 14>, <14, 14, 14>,
			<48, 48, 48>, <0, 0, 0>, <0, 0, 0>, <48, 48, 48>,
			<48, 48, 48>, <0, 0, 0>, <0, 0, 0>, <48, 48, 48>,
			<48, 48, 48>, <48, 48, 48>, <0, 0, 0>, <0, 0, 0>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<15, 15, 15>, <15, 15, 15>, <14, 14, 14>, <14, 14, 14>,
			<33, 33, 33>, <33, 33, 33>, <15, 15, 15>, <15, 15, 15>,
			<33, 33, 33>, <33, 33, 33>, <33, 33, 33>, <33, 33, 33>,
			<34, 34, 33>, <33, 34, 34>, <34, 34, 31>, <34, 31, 31>,
			<34, 34, 31>, <34, 31, 31>, <31, 31, 29>, <31, 29, 29>,
			<31, 31, 29>, <31, 29, 29>, <29, 29, 27>, <29, 27, 27>,
			<29, 29, 27>, <29, 27, 27>, <27, 27, 22>, <27, 22, 20>,
			<27, 27, 20>, <27, 20, 22>, <43, 43, 42>, <43, 42, 42>,
			<8, 8, 7>, <8, 7, 7>, <42, 42, 42>, <42, 42, 42>,
			<7, 7, 8>, <7, 8, 7>, <42, 42, 43>, <42, 43, 43>,
			<7, 8, 8>, <7, 8, 8>, <43, 43, 44>, <8, 9, 8>,
			<43, 43, 43>, <43, 43, 43>, <8, 8, 8>, <8, 8, 8>,
			<16, 16, 16>, <16, 16, 16>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <33, 33, 33>, <33, 33, 33>,
			<33, 33, 33>, <33, 33, 33>, <0, 0, 0>, <0, 0, 0>,
			<48, 48, 48>, <48, 48, 48>, <16, 16, 16>, <16, 16, 16>,
			<16, 16, 16>, <16, 16, 16>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <48, 48, 48>, <48, 48, 48>,
			<0, 0, 0>, <0, 0, 0>, <14, 14, 14>, <14, 14, 14>,
			<33, 33, 33>, <33, 33, 33>, <15, 15, 15>, <15, 15, 15>,
			<33, 33, 33>, <33, 33, 33>, <33, 32, 32>, <33, 32, 33>,
			<32, 30, 30>, <32, 30, 32>, <30, 28, 28>, <30, 28, 30>,
			<28, 23, 23>, <28, 23, 28>, <23, 20, 20>, <23, 20, 23>,
			<18, 20, 20>, <18, 20, 18>, <20, 22, 18>, <22, 20, 18>,
			<18, 18, 18>, <18, 18, 18>
		}
	}
}
#end

#include "lg_3938.inc" // Hinge  1 x  2 Top

#include "lg_3022.inc" // Plate  2 x  2

#include "lg_0314e.inc" // Hinge Plate  2 x  5 Top with Large Hole

#include "lg_4508.inc" // Turntable  2 x  2 Plate Base with Hinge

#include "lg_2654.inc" // Dish  2 x  2

#include "lg_4274.inc" // Technic Pin 1/2

#declare LDX_SEAT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3816
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(18, 37, 20, -10.5, 9.5, -1)
		matrix <1,0,0,0,0,-1,0,1,0,10,-16,4>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3817
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(18, 37, 20, 10.5, 9.5, -1)
		matrix <1,0,0,0,0,-1,0,1,0,10,-16,4>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_PILOT_dot_DAT
		matrix <1,0,0,0,0.98,-0.17,0,0.17,0.98,0,-59.450001,11.66>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_2717_dot_dat
		LDXSeamMatrix(80, 80, 67, 0, -40, 3.5)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor4 }
	}
// 4 10 -22 10 0 0 -1 0 1 0 1 0 0 axis_32s.dat
	object {
		lg_3938
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 20, 0, 6, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3022
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <1,0,0,0,0,1,0,-1,0,10,-28,30>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor4 }
	}
	object {
		lg_0314e
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 98, 0, -3, -41)
		matrix <-1,0,0,0,0,1,0,1,0,10,22,48>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_4508
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 54, 0, 4, -7)
		matrix <-1,0,0,0,0,1,0,1,0,10,-8,46>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2654
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <-1,0,0,0,0,1,0,1,0,10,-8,54>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <1,0,0,0,0,1,0,-1,0,10,-8,46>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_4274
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(24, 16, 16, -8, 0, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-22,10>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#include "lg_2452.inc" // Hinge Plate  1 x  2 with 3 Fingers On Side

#include "lg_2466.inc" // Panel  3 x  2 x  6

#include "lg_3937.inc" // Hinge  1 x  2 Base

#declare LDX_VISOR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_2452
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 34, 0, 2, -7)
		matrix <-1,0,0,0,1,0,0,0,-1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,16,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2466_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 144, 60, 0, 64, -20)
		matrix <1,0,0,0,1,0,0,0,1,10,24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
	object {
		lg_3022
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,160,10>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3938
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 20, 0, 6, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,168,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,136,20>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
}

#include "lg_4276b.inc" // Hinge Plate  1 x  2 with 2 Fingers and Hollow Studs

#declare LDX_SHLDUP_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <-1,0,0,0,1,0,0,0,-1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_BODYUP_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_SEAT_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_VISOR_dot_DAT
		matrix <1,0,0,0,0.71,-0.71,0,0.71,0.71,10,-107,69>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_SHLDUP_dot_DAT
		matrix <0,0.92,-0.39,0,-0.39,-0.92,-1,0,0,20,-69.889999,76.190002>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#declare LDX_TOP_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_WAIST_dot_DAT
		matrix <-1,0,0,0,-0.57,-0.82,0,-0.82,0.57,10,22.33,47.880001>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_BODYUP_dot_DAT
		matrix <1,0,0,0,0.94,-0.34,0,0.34,0.94,-20,-15.07,10.32>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#include "lg_4854.inc" // Slope Brick 45  4 x  4 Double Inverted with Open Center

#include "lg_2458.inc" // Brick  1 x  2 with Pin

#include "lg_4865a.inc" // Panel  1 x  2 x  1 with Square Corners

#include "lg_3710.inc" // Plate  1 x  4

#declare LDX_SHOULDR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4854
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4854_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15_slope }
	}
	object {
		lg_2458
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <0,0,-1,0,1,0,1,0,0,-40,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
// 0 -10 2 0 0 0 1 0 1 0 -1 0 0 axis_32s.dat
	object {
		lg_4865a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 24, 20, 0, 12, 0)
		matrix <0,0,-1,0,1,0,1,0,0,20,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-8,30>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,-8,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,-40,-16,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_2432
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 32, 20.000101, 0, 16, 0.000051)
		matrix <1,0,0,0,1,0,0,0,1,-10,-40,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2432
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 32, 20.000101, 0, 16, 0.000051)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,-40,30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#include "lg_6134.inc" // Hinge  2 x  2 Top

#declare LDX_ARMPIT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_6134
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 40, 0, 6, 10)
		matrix <1,0,0,0,0.97,-0.26,0,0.26,0.97,10,0,2>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,0.97,-0.26,0,0.26,0.97,10,-5,14>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <-1,0,0,0,1,0,0,0,-1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_SOCKETR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_SHOULDR_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_ARMPIT_dot_DAT
		matrix <0,0,-1,0,1,0,1,0,0,-10,-12,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-10,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#include "lg_3941.inc" // Brick  2 x  2 Round

#include "lg_3940.inc" // Support  2 x  2 x  2 Round

#include "lg_4590.inc" // Plate  1 x  4 Offset

#include "lg_3069b.inc" // Tile  1 x  2 with Groove

#include "lg_3062b.inc" // Brick  1 x  1 Round with Hollow Stud

#include "lg_4588.inc" // Brick  1 x  1 Round with Fins

#include "lg_4589.inc" // Cone  1 x  1

#declare LDX_UPARMR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3941
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3940
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 52, 40, 0, 22, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-72,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-96,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4590
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(76, 20, 28, 0, 6, 4)
		matrix <1,0,0,0,1,0,0,0,1,0,-80,10>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3069b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 20, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-88,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3062b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-64,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3062b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-64,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_4588
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <-0.382683,0,0.92388,0,1,0,-0.92388,0,-0.382683,-30,-104,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_4588
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <-0.92388,0,0.382683,0,1,0,-0.382683,0,-0.92388,30,-104,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_4589
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,-128,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_4589
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,-128,20>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#declare LDX_WRISTL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_2452
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 34, 0, 2, -7)
		matrix <-1,0,0,0,1,0,0,0,-1,0,-8,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2452
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 34, 0, 2, -7)
		matrix <1,0,0,0,1,0,0,0,1,0,-8,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#include "lg_2412a.inc" // Tile  1 x  2 Grille without Groove

#declare LDX_FINGERL1_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2412a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 20, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#declare LDX_FINGERL2_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2412a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 20, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#declare LDX_HANDL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_WRISTL_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_FINGERL1_dot_DAT
		matrix <0,0.97,0.28,0,-0.28,0.97,1,0,0,0,-41.59,14.87>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_FINGERL2_dot_DAT
		matrix <0,0.97,-0.26,0,-0.26,-0.97,-1,0,0,0,-42.040001,-15.59>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_4ARMR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		LDX_HANDL_dot_DAT
		matrix <0,0,-1,0,1,0,1,0,0,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3941
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3022
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6134
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 40, 0, 6, 10)
		matrix <1,0,0,0,1,0,0,0,1,0,40,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
// 0 0 50 -10 1 0 0 0 1 0 0 0 1 axis_32s.dat
}

#declare LDX_APPENDR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_UPARMR_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_4ARMR_dot_DAT
		matrix <1,0,0,0,0.71,0.71,0,-0.71,0.71,0,-128,-38>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_ARMR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_SOCKETR_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_APPENDR_dot_DAT
		matrix <0.84,0.22,-0.5,-0.26,0.97,0,0.48,0.13,0.87,4,-17,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#include "lg_6141.inc" // Plate  1 x  1 Round

#declare LDX_SPOT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		lg_6141_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
	object {
		lg_6141_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,20,24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
}

#include "lg_2444.inc" // Plate  2 x  2 with Hole and Split Underside Ribs

#include "lg_3665.inc" // Slope Brick 45  2 x  1 Inverted

#include "lg_6091.inc" // Brick  2 x  1 x  1 & 1/3 with Curved Top

#include "lg_4459.inc" // Technic Pin with Friction

#include "lg_6231.inc" // Panel  1 x  1 x  1 Corner with Rounded Corners

#declare LDX_KNEE_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6231
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 24, 20, 0, 12, 0)
		matrix <1,0,0,0,1,0,0,0,1,-10,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6231
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 24, 20, 0, 12, 0)
		matrix <0,0,-1,0,1,0,1,0,0,10,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_THIGHL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3940
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 52, 40, 0, 22, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2444
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 23, 40, 0, 7.5, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,56,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-10,64,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,10,48,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,72,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,72,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0_slope }
	}
	object {
		lg_3665
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,72,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,72,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0_slope }
	}
	object {
		lg_6091
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 32, 40, 0, 16, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,40,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6091
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 32, 40, 0, 16, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,40,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4459
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 16, 16, 0, 0, 0)
		matrix <1,0,0,0,1,0,0,0,1,20,66,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_KNEE_dot_DAT
		matrix <-1,0,0,0,1,0,0,0,-1,0,-32,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#include "lg_4858.inc" // Wedge  4 x  4

#include "lg_4286.inc" // Slope Brick 33  3 x  1

#include "lg_4859.inc" // Wing  3 x  4 with  1 x  2 Cutout without Stud Notches

#include "lg_3068b.inc" // Tile  2 x  2 with Groove

#include "lg_3020.inc" // Plate  2 x  4

#include "lg_3839b.inc" // Plate  1 x  2 with Handles Type 2

#declare LDX_FOOT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4858
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, -30)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4858_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, -30)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15_slope }
	}
	object {
		lg_4286
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 60, 0, 10, -20)
		matrix <-1,0,0,0,1,0,0,0,-1,30,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4286_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 60, 0, 10, -20)
		matrix <-1,0,0,0,1,0,0,0,-1,30,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15_slope }
	}
	object {
		lg_4286
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 60, 0, 10, -20)
		matrix <-1,0,0,0,1,0,0,0,-1,-30,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4286_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 60, 0, 10, -20)
		matrix <-1,0,0,0,1,0,0,0,-1,-30,0,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15_slope }
	}
	object {
		lg_4859
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 60, 0, 2, 10)
		matrix <1,0,0,0,1,0,0,0,1,0,24,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,30,24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,-30,24,30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,32,40>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,32,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,32,20>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,32,40>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,30,32,60>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,10,16,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4276b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-10,16,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,24,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3068b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,24,10>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,-30,32,60>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3020
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 40, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,0,32,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3839b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(60.000202, 14.000101, 40, 0, 3.000051, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,0,32,-60>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#include "lg_4150.inc" // Tile  2 x  2 Round with Cross Underside Stud

#include "lg_4476.inc" // Support  2 x  4 x  5 Stanchion Inclined

#include "lg_3021.inc" // Plate  2 x  3

#include "lg_4275b.inc" // Hinge Plate  1 x  2 with 3 Fingers and Hollow Studs

#declare LDX_SHIN_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4150
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40.001011, 8, 40.001011, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4476
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 124, 100, 0, 58, -30)
		matrix <1,0,0,0,1,0,0,0,1,10,24,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3021
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(60, 12, 40, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,10,8,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4275b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,0,16,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4275b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,20,16,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,16,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3020
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 40, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,10,144,-60>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4275b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(54, 12, 20, 7, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,20,16,-20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3938
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 20, 0, 6, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,152,-50>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_LEG_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_FOOT_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_SHIN_dot_DAT
		matrix <-1,0,0,0,-1,0,0,0,1,20,40,50>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#declare LDX_THIGHR_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3940
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 52, 40, 0, 22, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2444
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 23, 40, 0, 7.5, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,56,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,-10,64,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,10,48,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6091
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 32, 40, 0, 16, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,40,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6091
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 32, 40, 0, 16, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,40,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,72,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <-1,0,0,0,1,0,0,0,-1,-10,72,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0_slope }
	}
	object {
		lg_3665
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,72,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3665_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 40, 0, 10, -10)
		matrix <1,0,0,0,1,0,0,0,1,-10,72,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0_slope }
	}
	object {
		lg_4459
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 16, 16, 0, 0, 0)
		matrix <1,0,0,0,1,0,0,0,1,20,66,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_KNEE_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,-32,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_BOT_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_THIGHL_dot_DAT
		matrix <-1,0,0,0,-0.97,0.26,0,0.26,0.97,20,-138.369995,-5.8>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_LEG_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,10,8,-2>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_LEG_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,-70,8,-2>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_THIGHR_dot_DAT
		matrix <1,0,0,0,-0.97,0.26,0,-0.26,-0.97,-60,-137.940002,-6.39>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#declare LDX_SHOULDL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4854
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4854_slope
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 28, 80, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15_slope }
	}
	object {
		lg_2458
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, -10)
		matrix <0,0,1,0,1,0,-1,0,0,40,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
// 0 10 2 0 0 0 -1 0 1 0 1 0 0 axis_32s.dat
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-8,30>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-8,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3710
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(80, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,40,-16,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_3023
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 20, 0, 2, 0)
		matrix <0,0,-1,0,1,0,1,0,0,20,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_2432
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 32, 20.000101, 0, 16, 0.000051)
		matrix <1,0,0,0,1,0,0,0,1,10,-40,-30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_2432
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 32, 20.000101, 0, 16, 0.000051)
		matrix <-1,0,0,0,1,0,0,0,-1,10,-40,30>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4865a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 24, 20, 0, 12, 0)
		matrix <0,0,1,0,1,0,-1,0,0,-20,-8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#declare LDX_SOCKETL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_SHOULDL_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_ARMPIT_dot_DAT
		matrix <0,0,1,0,1,0,-1,0,0,20,-16,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_4ARML_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3680
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 40, 0, 4, 0)
		matrix <-1,0,0,0,1,0,0,0,-1,0,24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		LDX_HANDL_dot_DAT
		matrix <0,0,-1,0,1,0,1,0,0,0,24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3941
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,32,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3022
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,56,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6134
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 40, 0, 6, 10)
		matrix <1,0,0,0,1,0,0,0,1,0,64,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
// 7 0 74 -10 1 0 0 0 1 0 0 0 1 axis_32s.dat
}

#include "lg_4085c.inc" // Plate  1 x  1 with Clip Vertical (Thick U-Clip)

#include "lg_6019.inc" // Plate  1 x  1 with Clip Horizontal (Open U-Clip)

#declare LDX_UPARML_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3937
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 22, 20, 0, 13, 0)
		matrix <-1,0,0,0,1,0,0,0,-1,0,-96,10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4085c
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 34, 0, 2, -7)
		matrix <0,0,-1,0,1,0,1,0,0,-10,-80,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_6019
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 16, 34, 0, 2, -7)
		matrix <1,0,0,0,1,0,0,0,1,10,-80,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3069b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 8, 20, 0, 4, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-88,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3940
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 52, 40, 0, 22, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-72,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3941
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 28, 40, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_3679
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(35, 12, 35, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#include "lg_4360.inc" // Minifig Camera with Side Sight

#include "lg_3957a.inc" // Antenna  4H with Rounded Top

#include "lg_75535.inc" // Technic Pin Joiner Round

#declare LDX_GUN_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_4360
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(76, 38, 35.32, -6, 9, 7.66)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3957a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(16, 96, 16, 0, -40, 0)
		matrix <0,1,0,1,0,0,0,0,-1,-38,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_75535
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 20, 20, 0, 0, 0)
		matrix <1,0,0,0,-1,0,0,0,-1,-111,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		lg_3062b
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <0,0,-1,1,0,0,0,-1,0,42,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
}

#include "lg_4740.inc" // Dish  2 x  2 Inverted

#declare LDX_ILLUM_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		lg_3957a
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(16, 96, 16, 0, -40, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,0,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		lg_4589
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_4740
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(40, 12, 40, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,8,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		lg_6141_clear
		matrix <0,0,-25,-25,0,0,0,-25,0,0,0,0>
		LDXSeamMatrix(20, 12, 20, 0, 2, 0)
		matrix <1,0,0,0,1,0,0,0,1,10,16,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
}

#declare LDX_APPENDL_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_4ARML_dot_DAT
		matrix <0,0,-1,-0.71,0.71,0,0.71,0.71,0,44,26,20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_UPARML_dot_DAT
		matrix <0,0,1,-1,0,0,0,-1,0,-102,81,20>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_GUN_dot_DAT
		matrix <-1,0,0,0,0,-1,0,-1,0,-7.32,111,44>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_ILLUM_dot_DAT
		matrix <0,1,0,1,0,0,0,0,-1,32.68,81,-10>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_ARML_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_SOCKETL_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,160,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_APPENDL_dot_DAT
		matrix <-0.26,-0.97,0,-0.48,0.13,0.87,-0.84,0.22,-0.5,35,25,-61>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
}

#declare LDX_ROBO_dot_DAT = union {
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_TOP_dot_DAT
		matrix <1,0,0,0,0.81,0.59,0,-0.59,0.81,0,-316,-8>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_ARMR_dot_DAT
		matrix <-1,0,0,0,-1,-0.09,0,-0.09,1,-80,-355.959991,-5.05>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_SPOT_dot_DAT
		matrix <1,0,0,0,0.71,-0.71,0,0.71,0.71,-10,-306.980011,-51.060001>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_BOT_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,20,-47,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_ARML_dot_DAT
		matrix <-1,0,0,0,-1,-0.09,0,-0.09,1,90,-196.509995,9.35>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
}

#declare LDX_complete_dot_ldr = union {
// FILE complete.ldr
// New Model
// Name: complete.ldr
// Author: MLCad
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
// 16 0 0 0 1 0 0 0 1 0 0 0 1 axis_32s.dat
	object {
		LDX_ROBO_dot_DAT
		matrix <1,0,0,0,1,0,0,0,1,0,-1,-8>
	}
#if (LDXRefls = 0)
	no_reflection
#end
#if (LDXShads = 0)
	no_shadow
#end
}

// complete.ldr
object {
	LDX_complete_dot_ldr
	#if (version >= 3.1) material #else texture #end { LDXColor7 }
}

// Floor
#if (LDXFloor != 0)
object {
	plane { LDXFloorAxis, LDXFloorLoc hollow }
	texture {
		pigment { color rgb <LDXFloorR,LDXFloorG,LDXFloorB> }
		finish { ambient LDXFloorAmb diffuse LDXFloorDif }
	}
}
#end

