// Generated By: LDView 4.4 Alpha 5 Copyright (C) 2019 Travis Cobbs & Peter Bartfai
// See: https://tcobbs.github.io/ldview/
// Date: Mon Jul  8 17:42:48 2019
// Input LDraw File: every_color.ldr
// LDraw File Author: MLCad
//
// This file was automatically generated from an LDraw file by the program
// LDView.  See comments above for further details.

#version 3.7;

#if (version >= 3.7) global_settings {assumed_gamma 1} #end

#ifndef (LDXQual) #declare LDXQual = 3; #end	// Quality (0 = Bounding Box; 1 = No Refraction; 2 = Normal; 3 = Stud Logos)
#ifndef (LDXSW) #declare LDXSW = 0.5; #end	// Seam Width (0 for no seams)
#ifndef (LDXStuds) #declare LDXStuds = 1; #end	// Show studs? (1 = YES; 0 = NO)
#ifndef (LDXRefls) #declare LDXRefls = 1; #end	// Reflections? (1 = YES; 0 = NO)
#ifndef (LDXShads) #declare LDXShads = 1; #end	// Shadows? (1 = YES; 0 = NO)
#ifndef (LDXBackground) #declare LDXBackground = 0; #end	// Include Background? (1 = YES; 0 = NO)
#ifndef (LDXFloor) #declare LDXFloor = 0; #end	// Include Floor? (1 = YES; 0 = NO)

// Model bounds information
#ifndef (LDXMinX) #declare LDXMinX = -9.75; #end
#ifndef (LDXMinY) #declare LDXMinY = -27.75; #end
#ifndef (LDXMinZ) #declare LDXMinZ = -9.75; #end
#ifndef (LDXMaxX) #declare LDXMaxX = 9.75; #end
#ifndef (LDXMaxY) #declare LDXMaxY = -0.25; #end
#ifndef (LDXMaxZ) #declare LDXMaxZ = 9.75; #end
#ifndef (LDXCenterX) #declare LDXCenterX = 0; #end
#ifndef (LDXCenterY) #declare LDXCenterY = -14; #end
#ifndef (LDXCenterZ) #declare LDXCenterZ = 0; #end
#ifndef (LDXCenter) #declare LDXCenter = <LDXCenterX,LDXCenterY,LDXCenterZ>; #end
#ifndef (LDXRadius) #declare LDXRadius = 19.472738; #end

// Camera settings
#ifndef (LDXCameraLoc) #declare LDXCameraLoc = < 31.160398,-39.44236,-31.160398 >; #end	// Camera Location vector
#ifndef (LDXCameraLookAt) #declare LDXCameraLookAt = < -5.05583072053737936358,-9.87193368142768434836,5.05583072053737936358 >; #end	// Camera look-at point vector
#ifndef (LDXCameraSky) #declare LDXCameraSky = < -0.35355339491603171576,-0.8660254002549215846,0.35355339491603171576 >; #end	// Camera sky vector (<0,-1,0> will usually work for standard "up")
#ifndef (LDXCameraAngle) #declare LDXCameraAngle = 76.900337; #end
#ifndef (LDXCameraAspect) #declare LDXCameraAspect = image_width/image_height; #end
#ifndef (LDXCameraTransform) #declare LDXCameraTransform = transform {}; #end

#ifndef (LDXFloorLoc) #declare LDXFloorLoc = LDXMaxY; #end	// Floor location. (Dependent on floor axis; MAX_Y is bottom of model)
#ifndef (LDXFloorAxis) #declare LDXFloorAxis = y; #end	// Floor axis (x, y, or z)
#ifndef (LDXFloorR) #declare LDXFloorR = 0.8; #end	// Floor Red
#ifndef (LDXFloorG) #declare LDXFloorG = 0.8; #end	// Floor Green
#ifndef (LDXFloorB) #declare LDXFloorB = 0.8; #end	// Floor Blue
#ifndef (LDXFloorAmb) #declare LDXFloorAmb = 0.4; #end	// Floor Ambient
#ifndef (LDXFloorDif) #declare LDXFloorDif = 0.4; #end	// Floor Diffuse
#ifndef (LDXAmb) #declare LDXAmb = 0.4; #end
#ifndef (LDXDif) #declare LDXDif = 0.4; #end
#ifndef (LDXRefl) #declare LDXRefl = 0.08; #end
#ifndef (LDXPhong) #declare LDXPhong = 0.5; #end
#ifndef (LDXPhongS) #declare LDXPhongS = 40; #end
#ifndef (LDXTRefl) #declare LDXTRefl = 0.2; #end
#ifndef (LDXTFilt) #declare LDXTFilt = 0.85; #end
#ifndef (LDXIoR) #declare LDXIoR = 1.25; #end
#ifndef (LDXRubberRefl) #declare LDXRubberRefl = 0; #end
#ifndef (LDXRubberPhong) #declare LDXRubberPhong = 0.1; #end
#ifndef (LDXRubberPhongS) #declare LDXRubberPhongS = 10; #end
#ifndef (LDXChromeRefl) #declare LDXChromeRefl = 0.85; #end
#ifndef (LDXChromeBril) #declare LDXChromeBril = 5; #end
#ifndef (LDXChromeSpec) #declare LDXChromeSpec = 0.8; #end
#ifndef (LDXChromeRough) #declare LDXChromeRough = 0.01; #end
#ifndef (LDXOpaqueNormal) #declare LDXOpaqueNormal = normal { bumps 0.001 scale 0.5 }; #end
#ifndef (LDXTransNormal) #declare LDXTransNormal = normal { bumps 0.001 scale 0.5 }; #end
#ifndef (LDXIPov) #declare LDXIPov = 0; #end	// Use inline POV code from LDraw file? (1 = YES; 0 = NO)
#ifndef (LDXBgR) #declare LDXBgR = 0.752941; #end	// Background Red
#ifndef (LDXBgG) #declare LDXBgG = 0.752941; #end	// Background Green
#ifndef (LDXBgB) #declare LDXBgB = 0.752941; #end	// Background Blue

// Camera
#ifndef (LDXSkipCamera)
camera {
	location LDXCameraLoc
	sky LDXCameraSky
	right LDXCameraAspect * < -1,0,0 >
	look_at LDXCameraLookAt
	angle LDXCameraAngle
	transform {LDXCameraTransform}
}
#end

// Lights
#ifndef (LDXSkipLight1)
light_source {	// Latitude,Longitude: 45,0,LDXRadius*2
	<0*LDXRadius,-1.414214*LDXRadius,-1.414214*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight2)
light_source {	// Latitude,Longitude: 30,120,LDXRadius*2
	<1.5*LDXRadius,-1*LDXRadius,0.866026*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end
#ifndef (LDXSkipLight3)
light_source {	// Latitude,Longitude: 60,-120,LDXRadius*2
	<-0.866025*LDXRadius,-1.732051*LDXRadius,0.5*LDXRadius> + LDXCenter
	color rgb <1,1,1>
}
#end

#macro LDXSeamMatrix(Width, Height, Depth, CenterX, CenterY, CenterZ)
#local aw = 0;
#local ah = 0;
#local ad = 0;
#local ax = 0;
#local ay = 0;
#local az = 0;
#if (Width != 0)
#local aw = 1-LDXSW/Width;
#end
#if (Height != 0)
#local ah = 1-LDXSW/Height;
#end
#if (Depth != 0)
#local ad = 1-LDXSW/Depth;
#end
#if (Width != 0 & CenterX != 0)
#local ax = LDXSW/(Width / CenterX);
#end
#if (Height != 0 & CenterY != 0)
#local ay = LDXSW/(Height / CenterY);
#end
#if (Depth != 0 & CenterZ != 0)
#local az = LDXSW/(Depth / CenterZ);
#end
#if (aw <= 0)
#local aw = 1;
#local ax = 0;
#end
#if (ah <= 0)
#local ah = 1;
#local ay = 0;
#end
#if (ad <= 0)
#local ad = 1;
#local az = 0;
#end
matrix <aw,0,0,0,ah,0,0,0,ad,ax,ay,az>
#end


#if (LDXBackground != 0)
#if (version >= 3.7)
background { color srgb <LDXBgR,LDXBgG,LDXBgB> }
#else
background { color rgb <LDXBgR,LDXBgG,LDXBgB> }
#end
#end

#ifndef (LDXSkipOpaqueColorMacro)
#macro LDXOpaqueColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
#if (version >= 3.7)
		pigment { srgbf <r,g,b,0> }
#else
		pigment { rgbf <r,g,b,0> }
#end
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXRefl }
		normal { LDXOpaqueNormal }
#end
	}
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor0) // Black
#declare LDXColor0 = LDXOpaqueColor(0.019608,0.07451,0.113725)
#end

#ifndef (LDXColor1) // Blue
#declare LDXColor1 = LDXOpaqueColor(0,0.333333,0.74902)
#end

#ifndef (LDXColor2) // Green
#declare LDXColor2 = LDXOpaqueColor(0.145098,0.478431,0.243137)
#end

#ifndef (LDXColor3) // Dark Turquoise
#declare LDXColor3 = LDXOpaqueColor(0,0.513725,0.560784)
#end

#ifndef (LDXColor4) // Red
#declare LDXColor4 = LDXOpaqueColor(0.788235,0.101961,0.035294)
#end

#ifndef (LDXColor5) // Dark Pink
#declare LDXColor5 = LDXOpaqueColor(0.784314,0.439216,0.627451)
#end

#ifndef (LDXColor6) // Brown
#declare LDXColor6 = LDXOpaqueColor(0.345098,0.223529,0.152941)
#end

#ifndef (LDXColor7) // Light Grey
#declare LDXColor7 = LDXOpaqueColor(0.607843,0.631373,0.615686)
#end

#ifndef (LDXColor8) // Dark Grey
#declare LDXColor8 = LDXOpaqueColor(0.427451,0.431373,0.360784)
#end

#ifndef (LDXColor9) // Light Blue
#declare LDXColor9 = LDXOpaqueColor(0.705882,0.823529,0.890196)
#end

#ifndef (LDXColor10) // Bright Green
#declare LDXColor10 = LDXOpaqueColor(0.294118,0.623529,0.290196)
#end

#ifndef (LDXColor11) // Light Turquoise
#declare LDXColor11 = LDXOpaqueColor(0.333333,0.647059,0.686275)
#end

#ifndef (LDXColor12) // Salmon
#declare LDXColor12 = LDXOpaqueColor(0.94902,0.439216,0.368627)
#end

#ifndef (LDXColor13) // Pink
#declare LDXColor13 = LDXOpaqueColor(0.988235,0.592157,0.67451)
#end

#ifndef (LDXColor14) // Yellow
#declare LDXColor14 = LDXOpaqueColor(0.94902,0.803922,0.215686)
#end

#ifndef (LDXColor15) // White
#declare LDXColor15 = LDXOpaqueColor(1,1,1)
#end

#ifndef (LDXColor17) // Light Green
#declare LDXColor17 = LDXOpaqueColor(0.760784,0.854902,0.721569)
#end

#ifndef (LDXColor18) // Light Yellow
#declare LDXColor18 = LDXOpaqueColor(0.984314,0.901961,0.588235)
#end

#ifndef (LDXColor19) // Tan
#declare LDXColor19 = LDXOpaqueColor(0.894118,0.803922,0.619608)
#end

#ifndef (LDXColor20) // Light Violet
#declare LDXColor20 = LDXOpaqueColor(0.788235,0.792157,0.886275)
#end

#ifndef (LDXSkipTransColorMacro)
#macro LDXTransColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
#if (version >= 3.7)
		pigment { #if (LDXQual > 1) srgbf <r,g,b,LDXTFilt> #else srgbf <0.6,0.6,0.6,0> #end }
#else
		pigment { #if (LDXQual > 1) rgbf <r,g,b,LDXTFilt> #else rgbf <0.6,0.6,0.6,0> #end }
#end
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXTRefl }
		normal { LDXTransNormal }
		#if (version >= 3.1) #else finish { refraction 1 ior LDXIoR } #end
#end
	}
#if (version >= 3.1) #if (LDXQual > 1)
	interior { ior LDXIoR }
#end #end
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor21) // Glow In Dark Opaque
#declare LDXColor21 = LDXTransColor(0.987843,1,0.96902)
#end

#ifndef (LDXColor22) // Purple
#declare LDXColor22 = LDXOpaqueColor(0.505882,0,0.482353)
#end

#ifndef (LDXColor23) // Dark Blue Violet
#declare LDXColor23 = LDXOpaqueColor(0.12549,0.196078,0.690196)
#end

#ifndef (LDXColor24) // Edge Colour
#declare LDXColor24 = LDXOpaqueColor(0.498039,0.498039,0.498039)
#end

#ifndef (LDXColor25) // Orange
#declare LDXColor25 = LDXOpaqueColor(0.996078,0.541176,0.094118)
#end

#ifndef (LDXColor26) // Magenta
#declare LDXColor26 = LDXOpaqueColor(0.572549,0.223529,0.470588)
#end

#ifndef (LDXColor27) // Lime
#declare LDXColor27 = LDXOpaqueColor(0.733333,0.913725,0.043137)
#end

#ifndef (LDXColor28) // Dark Tan
#declare LDXColor28 = LDXOpaqueColor(0.584314,0.541176,0.45098)
#end

#ifndef (LDXColor29) // Bright Pink
#declare LDXColor29 = LDXOpaqueColor(0.894118,0.678431,0.784314)
#end

#ifndef (LDXColor30) // Medium Lavender
#declare LDXColor30 = LDXOpaqueColor(0.67451,0.470588,0.729412)
#end

#ifndef (LDXColor31) // Lavender
#declare LDXColor31 = LDXOpaqueColor(0.882353,0.835294,0.929412)
#end

#ifndef (LDXColor32) // Trans Black IR Lens
#declare LDXColor32 = LDXTransColor(0,0,0)
#end

#ifndef (LDXColor33) // Trans Dark Blue
#declare LDXColor33 = LDXTransColor(0,0.188235,0.962745)
#end

#ifndef (LDXColor34) // Trans Green
#declare LDXColor34 = LDXTransColor(0.205882,0.705882,0.382353)
#end

#ifndef (LDXColor35) // Trans Bright Green
#declare LDXColor35 = LDXTransColor(0.505882,0.990196,0.411765)
#end

#ifndef (LDXColor36) // Trans Red
#declare LDXColor36 = LDXTransColor(0.978824,0.152941,0.052941)
#end

#ifndef (LDXColor37) // Trans Dark Pink
#declare LDXColor37 = LDXTransColor(0.987451,0.6,0.958431)
#end

#ifndef (LDXColor38) // Trans Neon Orange
#declare LDXColor38 = LDXTransColor(1,0.950196,0.076471)
#end

#ifndef (LDXColor39) // Trans Very Light Blue
#declare LDXColor39 = LDXTransColor(0.975686,0.987451,0.994118)
#end

#ifndef (LDXColor40) // Trans Black
#declare LDXColor40 = LDXTransColor(0.582353,0.558824,0.482353)
#end

#ifndef (LDXColor41) // Trans Medium Blue
#declare LDXColor41 = LDXTransColor(0.5,0.960392,0.971765)
#end

#ifndef (LDXColor42) // Trans Neon Green
#declare LDXColor42 = LDXTransColor(0.975294,1,0)
#end

#ifndef (LDXColor43) // Trans Light Blue
#declare LDXColor43 = LDXTransColor(0.968235,0.991373,0.993725)
#end

#ifndef (LDXColor44) // Trans Bright Reddish Lilac
#declare LDXColor44 = LDXTransColor(0.958824,0.658824,0.962353)
#end

#ifndef (LDXColor45) // Trans Pink
#declare LDXColor45 = LDXTransColor(0.998824,0.959216,0.967451)
#end

#ifndef (LDXColor46) // Trans Yellow
#declare LDXColor46 = LDXTransColor(0.996078,0.980392,0.276471)
#end

#ifndef (LDXColor47) // Trans Clear
#declare LDXColor47 = LDXTransColor(0.998824,0.998824,0.998824)
#end

#ifndef (LDXColor52) // Trans Purple
#declare LDXColor52 = LDXTransColor(0.964706,0.964706,0.979608)
#end

#ifndef (LDXColor54) // Trans Neon Yellow
#declare LDXColor54 = LDXTransColor(0.98549,0.96902,0)
#end

#ifndef (LDXColor57) // Trans Orange
#declare LDXColor57 = LDXTransColor(0.994118,0.956078,0.164706)
#end

#ifndef (LDXSkipChromeColorMacro)
#macro LDXChromeColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
#if (version >= 3.7)
		pigment { srgbf <r,g,b,0> }
#else
		pigment { rgbf <r,g,b,0> }
#end
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXPhong phong_size LDXPhongS reflection LDXChromeRefl brilliance LDXChromeBril metallic specular LDXChromeSpec roughness LDXChromeRough}
#end
	}
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor60) // Chrome Antique Brass
#declare LDXColor60 = LDXChromeColor(0.392157,0.352941,0.298039)
#end

#ifndef (LDXColor61) // Chrome Blue
#declare LDXColor61 = LDXChromeColor(0.423529,0.588235,0.74902)
#end

#ifndef (LDXColor62) // Chrome Green
#declare LDXColor62 = LDXChromeColor(0.235294,0.701961,0.443137)
#end

#ifndef (LDXColor63) // Chrome Pink
#declare LDXColor63 = LDXChromeColor(0.666667,0.301961,0.556863)
#end

#ifndef (LDXColor64) // Chrome Black
#declare LDXColor64 = LDXChromeColor(0.105882,0.164706,0.203922)
#end

#ifndef (LDXSkipRubberColorMacro)
#macro LDXRubberColor(r, g, b)
#if (version >= 3.1) material { #end
	texture {
#if (version >= 3.7)
		pigment { srgbf <r,g,b,0> }
#else
		pigment { rgbf <r,g,b,0> }
#end
#if (LDXQual > 1)
		finish { ambient LDXAmb diffuse LDXDif }
		finish { phong LDXRubberPhong phong_size LDXRubberPhongS reflection LDXRubberRefl }
#end
	}
#if (version >= 3.1) } #end
#end
#end

#ifndef (LDXColor65) // Rubber Yellow
#declare LDXColor65 = LDXRubberColor(0.960784,0.803922,0.184314)
#end

#ifndef (LDXColor66) // Rubber Trans Yellow
#declare LDXColor66 = LDXTransColor(0.979216,0.96902,0)
#end

#ifndef (LDXColor67) // Rubber Trans Clear
#declare LDXColor67 = LDXTransColor(1,1,1)
#end

#ifndef (LDXColor68) // Very Light Orange
#declare LDXColor68 = LDXOpaqueColor(0.952941,0.811765,0.607843)
#end

#ifndef (LDXColor69) // Bright Reddish Lilac
#declare LDXColor69 = LDXOpaqueColor(0.803922,0.384314,0.596078)
#end

#ifndef (LDXColor70) // Reddish Brown
#declare LDXColor70 = LDXOpaqueColor(0.345098,0.164706,0.070588)
#end

#ifndef (LDXColor71) // Light Bluish Grey
#declare LDXColor71 = LDXOpaqueColor(0.627451,0.647059,0.662745)
#end

#ifndef (LDXColor72) // Dark Bluish Grey
#declare LDXColor72 = LDXOpaqueColor(0.423529,0.431373,0.407843)
#end

#ifndef (LDXColor73) // Medium Blue
#declare LDXColor73 = LDXOpaqueColor(0.360784,0.615686,0.819608)
#end

#ifndef (LDXColor74) // Medium Green
#declare LDXColor74 = LDXOpaqueColor(0.45098,0.862745,0.631373)
#end

#ifndef (LDXColor75) // Speckle Black Copper
#declare LDXColor75 = LDXOpaqueColor(0,0,0)
#end

#ifndef (LDXColor76) // Speckle Dark Bluish Grey Silver
#declare LDXColor76 = LDXOpaqueColor(0.388235,0.372549,0.380392)
#end

#ifndef (LDXColor77) // Light Pink
#declare LDXColor77 = LDXOpaqueColor(0.996078,0.8,0.811765)
#end

#ifndef (LDXColor78) // Light Flesh
#declare LDXColor78 = LDXOpaqueColor(0.964706,0.843137,0.701961)
#end

#ifndef (LDXColor79) // Milky White
#declare LDXColor79 = LDXTransColor(1,1,1)
#end

#ifndef (LDXColor80) // Metallic Silver
#declare LDXColor80 = LDXOpaqueColor(0.647059,0.662745,0.705882)
#end

#ifndef (LDXColor81) // Metallic Green
#declare LDXColor81 = LDXOpaqueColor(0.537255,0.607843,0.372549)
#end

#ifndef (LDXColor82) // Metallic Gold
#declare LDXColor82 = LDXOpaqueColor(0.858824,0.67451,0.203922)
#end

#ifndef (LDXColor83) // Metallic Black
#declare LDXColor83 = LDXOpaqueColor(0.101961,0.156863,0.192157)
#end

#ifndef (LDXColor84) // Medium Dark Flesh
#declare LDXColor84 = LDXOpaqueColor(0.8,0.439216,0.164706)
#end

#ifndef (LDXColor85) // Medium Lilac
#declare LDXColor85 = LDXOpaqueColor(0.247059,0.211765,0.568627)
#end

#ifndef (LDXColor86) // Dark Flesh
#declare LDXColor86 = LDXOpaqueColor(0.486275,0.313725,0.227451)
#end

#ifndef (LDXColor87) // Metallic Dark Grey
#declare LDXColor87 = LDXOpaqueColor(0.427451,0.431373,0.360784)
#end

#ifndef (LDXColor89) // Blue Violet
#declare LDXColor89 = LDXOpaqueColor(0.298039,0.380392,0.858824)
#end

#ifndef (LDXColor92) // Flesh
#declare LDXColor92 = LDXOpaqueColor(0.815686,0.568627,0.407843)
#end

#ifndef (LDXColor100) // Light Salmon
#declare LDXColor100 = LDXOpaqueColor(0.996078,0.729412,0.741176)
#end

#ifndef (LDXColor110) // Violet
#declare LDXColor110 = LDXOpaqueColor(0.262745,0.329412,0.639216)
#end

#ifndef (LDXColor112) // Medium Violet
#declare LDXColor112 = LDXOpaqueColor(0.407843,0.454902,0.792157)
#end

#ifndef (LDXColor114) // Glitter Trans Dark Pink
#declare LDXColor114 = LDXTransColor(0.987451,0.6,0.958431)
#end

#ifndef (LDXColor115) // Medium Lime
#declare LDXColor115 = LDXOpaqueColor(0.780392,0.823529,0.235294)
#end

#ifndef (LDXColor117) // Glitter Trans Clear
#declare LDXColor117 = LDXTransColor(1,1,1)
#end

#ifndef (LDXColor118) // Aqua
#declare LDXColor118 = LDXOpaqueColor(0.701961,0.843137,0.819608)
#end

#ifndef (LDXColor120) // Light Lime
#declare LDXColor120 = LDXOpaqueColor(0.85098,0.894118,0.654902)
#end

#ifndef (LDXColor125) // Light Orange
#declare LDXColor125 = LDXOpaqueColor(0.976471,0.729412,0.380392)
#end

#ifndef (LDXColor128) // Dark Nougat
#declare LDXColor128 = LDXOpaqueColor(0.678431,0.380392,0.25098)
#end

#ifndef (LDXColor129) // Glitter Trans Purple
#declare LDXColor129 = LDXTransColor(0.588235,0,0.570588)
#end

#ifndef (LDXColor132) // Speckle Black Silver
#declare LDXColor132 = LDXOpaqueColor(0,0,0)
#end

#ifndef (LDXColor133) // Speckle Black Gold
#declare LDXColor133 = LDXOpaqueColor(0,0,0)
#end

#ifndef (LDXColor134) // Copper
#declare LDXColor134 = LDXOpaqueColor(0.588235,0.290196,0.152941)
#end

#ifndef (LDXColor135) // Pearl Light Grey
#declare LDXColor135 = LDXOpaqueColor(0.611765,0.639216,0.658824)
#end

#ifndef (LDXColor137) // Metal Blue
#declare LDXColor137 = LDXOpaqueColor(0.337255,0.466667,0.729412)
#end

#ifndef (LDXColor142) // Pearl Light Gold
#declare LDXColor142 = LDXOpaqueColor(0.862745,0.745098,0.380392)
#end

#ifndef (LDXColor148) // Pearl Dark Grey
#declare LDXColor148 = LDXOpaqueColor(0.341176,0.345098,0.341176)
#end

#ifndef (LDXColor150) // Pearl Very Light Grey
#declare LDXColor150 = LDXOpaqueColor(0.733333,0.741176,0.737255)
#end

#ifndef (LDXColor151) // Very Light Bluish Grey
#declare LDXColor151 = LDXOpaqueColor(0.901961,0.890196,0.878431)
#end

#ifndef (LDXColor178) // Flat Dark Gold
#declare LDXColor178 = LDXOpaqueColor(0.705882,0.533333,0.243137)
#end

#ifndef (LDXColor179) // Flat Silver
#declare LDXColor179 = LDXOpaqueColor(0.537255,0.529412,0.533333)
#end

#ifndef (LDXColor183) // Pearl White
#declare LDXColor183 = LDXOpaqueColor(0.94902,0.952941,0.94902)
#end

#ifndef (LDXColor184) // Metallic Bright Red
#declare LDXColor184 = LDXOpaqueColor(0.839216,0,0.14902)
#end

#ifndef (LDXColor186) // Metallic Dark Green
#declare LDXColor186 = LDXOpaqueColor(0,0.556863,0.235294)
#end

#ifndef (LDXColor189) // Reddish Gold
#declare LDXColor189 = LDXOpaqueColor(0.67451,0.509804,0.278431)
#end

#ifndef (LDXColor191) // Bright Light Orange
#declare LDXColor191 = LDXOpaqueColor(0.972549,0.733333,0.239216)
#end

#ifndef (LDXColor212) // Bright Light Blue
#declare LDXColor212 = LDXOpaqueColor(0.52549,0.756863,0.882353)
#end

#ifndef (LDXColor216) // Rust
#declare LDXColor216 = LDXOpaqueColor(0.701961,0.062745,0.015686)
#end

#ifndef (LDXColor218) // Reddish Lilac
#declare LDXColor218 = LDXOpaqueColor(0.556863,0.333333,0.592157)
#end

#ifndef (LDXColor219) // Lilac
#declare LDXColor219 = LDXOpaqueColor(0.337255,0.305882,0.615686)
#end

#ifndef (LDXColor226) // Bright Light Yellow
#declare LDXColor226 = LDXOpaqueColor(1,0.941176,0.227451)
#end

#ifndef (LDXColor231) // Trans Bright Light Orange
#declare LDXColor231 = LDXTransColor(0.998824,0.971765,0.641176)
#end

#ifndef (LDXColor232) // Sky Blue
#declare LDXColor232 = LDXOpaqueColor(0.337255,0.745098,0.839216)
#end

#ifndef (LDXColor234) // Trans Fire Yellow
#declare LDXColor234 = LDXTransColor(0.998431,0.99098,0.956471)
#end

#ifndef (LDXColor256) // Rubber Black
#declare LDXColor256 = LDXRubberColor(0.129412,0.129412,0.129412)
#end

#ifndef (LDXColor272) // Dark Blue
#declare LDXColor272 = LDXOpaqueColor(0.05098,0.196078,0.356863)
#end

#ifndef (LDXColor273) // Rubber Blue
#declare LDXColor273 = LDXRubberColor(0,0.2,0.698039)
#end

#ifndef (LDXColor284) // Trans Reddish Lilac
#declare LDXColor284 = LDXTransColor(0.976078,0.950588,0.964706)
#end

#ifndef (LDXColor285) // Trans Light Green
#declare LDXColor285 = LDXTransColor(0.735294,0.976078,0.956863)
#end

#ifndef (LDXColor288) // Dark Green
#declare LDXColor288 = LDXOpaqueColor(0.094118,0.27451,0.196078)
#end

#ifndef (LDXColor293) // Trans Light Blue Violet
#declare LDXColor293 = LDXTransColor(0.629412,0.967059,0.989412)
#end

#ifndef (LDXColor294) // Glow In Dark Trans
#declare LDXColor294 = LDXTransColor(0.974118,0.977647,0.967843)
#end

#ifndef (LDXColor295) // Flamingo Pink
#declare LDXColor295 = LDXOpaqueColor(1,0.580392,0.760784)
#end

#ifndef (LDXColor297) // Pearl Gold
#declare LDXColor297 = LDXOpaqueColor(0.8,0.611765,0.168627)
#end

#ifndef (LDXColor300) // Metallic Copper
#declare LDXColor300 = LDXOpaqueColor(0.760784,0.498039,0.32549)
#end

#ifndef (LDXColor302) // Glitter Trans Light Blue
#declare LDXColor302 = LDXTransColor(0.968235,0.991373,0.993725)
#end

#ifndef (LDXColor308) // Dark Brown
#declare LDXColor308 = LDXOpaqueColor(0.207843,0.129412,0)
#end

#ifndef (LDXColor313) // Maersk Blue
#declare LDXColor313 = LDXOpaqueColor(0.329412,0.662745,0.784314)
#end

#ifndef (LDXColor320) // Dark Red
#declare LDXColor320 = LDXOpaqueColor(0.447059,0.054902,0.058824)
#end

#ifndef (LDXColor321) // Dark Azure
#declare LDXColor321 = LDXOpaqueColor(0.078431,0.596078,0.843137)
#end

#ifndef (LDXColor322) // Medium Azure
#declare LDXColor322 = LDXOpaqueColor(0.243137,0.760784,0.866667)
#end

#ifndef (LDXColor323) // Light Aqua
#declare LDXColor323 = LDXOpaqueColor(0.741176,0.862745,0.847059)
#end

#ifndef (LDXColor324) // Rubber Red
#declare LDXColor324 = LDXRubberColor(0.768627,0,0.14902)
#end

#ifndef (LDXColor326) // Yellowish Green
#declare LDXColor326 = LDXOpaqueColor(0.87451,0.933333,0.647059)
#end

#ifndef (LDXColor329) // Glow In Dark White
#declare LDXColor329 = LDXTransColor(0.996078,0.995294,0.984314)
#end

#ifndef (LDXColor330) // Olive Green
#declare LDXColor330 = LDXOpaqueColor(0.607843,0.603922,0.352941)
#end

#ifndef (LDXColor334) // Chrome Gold
#declare LDXColor334 = LDXChromeColor(0.733333,0.647059,0.239216)
#end

#ifndef (LDXColor335) // Sand Red
#declare LDXColor335 = LDXOpaqueColor(0.839216,0.458824,0.447059)
#end

#ifndef (LDXColor339) // Glitter Trans Neon Green
#declare LDXColor339 = LDXTransColor(0.975294,1,0)
#end

#ifndef (LDXColor350) // Rubber Orange
#declare LDXColor350 = LDXRubberColor(0.815686,0.4,0.062745)
#end

#ifndef (LDXColor351) // Medium Dark Pink
#declare LDXColor351 = LDXOpaqueColor(0.968627,0.521569,0.694118)
#end

#ifndef (LDXColor353)
#declare LDXColor353 = LDXOpaqueColor(0.2,0.2,0.34902)
#end

#ifndef (LDXColor366) // Earth Orange
#declare LDXColor366 = LDXOpaqueColor(0.980392,0.611765,0.109804)
#end

#ifndef (LDXColor373) // Sand Purple
#declare LDXColor373 = LDXOpaqueColor(0.517647,0.368627,0.517647)
#end

#ifndef (LDXColor375) // Rubber Light Grey
#declare LDXColor375 = LDXRubberColor(0.756863,0.760784,0.756863)
#end

#ifndef (LDXColor378) // Sand Green
#declare LDXColor378 = LDXOpaqueColor(0.627451,0.737255,0.67451)
#end

#ifndef (LDXColor379) // Sand Blue
#declare LDXColor379 = LDXOpaqueColor(0.34902,0.443137,0.517647)
#end

#ifndef (LDXColor383) // Chrome Silver
#declare LDXColor383 = LDXChromeColor(0.878431,0.878431,0.878431)
#end

#ifndef (LDXColor406) // Rubber Dark Blue
#declare LDXColor406 = LDXRubberColor(0,0.113725,0.407843)
#end

#ifndef (LDXColor449) // Rubber Purple
#declare LDXColor449 = LDXRubberColor(0.505882,0,0.482353)
#end

#ifndef (LDXColor450) // Fabuland Brown
#declare LDXColor450 = LDXOpaqueColor(0.713725,0.482353,0.313725)
#end

#ifndef (LDXColor462) // Medium Orange
#declare LDXColor462 = LDXOpaqueColor(1,0.654902,0.043137)
#end

#ifndef (LDXColor484) // Dark Orange
#declare LDXColor484 = LDXOpaqueColor(0.662745,0.333333,0)
#end

#ifndef (LDXColor490) // Rubber Lime
#declare LDXColor490 = LDXRubberColor(0.843137,0.941176,0)
#end

#ifndef (LDXColor493) // Magnet
#declare LDXColor493 = LDXOpaqueColor(0.396078,0.403922,0.380392)
#end

#ifndef (LDXColor494) // Electric Contact Alloy
#declare LDXColor494 = LDXOpaqueColor(0.815686,0.815686,0.815686)
#end

#ifndef (LDXColor495) // Electric Contact Copper
#declare LDXColor495 = LDXOpaqueColor(0.682353,0.478431,0.34902)
#end

#ifndef (LDXColor496) // Rubber Light Bluish Grey
#declare LDXColor496 = LDXRubberColor(0.639216,0.635294,0.643137)
#end

#ifndef (LDXColor503) // Very Light Grey
#declare LDXColor503 = LDXOpaqueColor(0.901961,0.890196,0.854902)
#end

#ifndef (LDXColor504) // Rubber Flat Silver
#declare LDXColor504 = LDXRubberColor(0.537255,0.529412,0.533333)
#end

#ifndef (LDXColor507)
#declare LDXColor507 = LDXOpaqueColor(0.835294,0.996078,0.988235)
#end

#ifndef (LDXColor508)
#declare LDXColor508 = LDXOpaqueColor(1,0.498039,0.498039)
#end

#ifndef (LDXColor509)
#declare LDXColor509 = LDXOpaqueColor(1,0.843137,0.898039)
#end

#ifndef (LDXColor511) // Rubber White
#declare LDXColor511 = LDXRubberColor(0.980392,0.980392,0.980392)
#end

#ifndef (LDXColor10002)
#declare LDXColor10002 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10026)
#declare LDXColor10026 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10031)
#declare LDXColor10031 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10070)
#declare LDXColor10070 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10226)
#declare LDXColor10226 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10308)
#declare LDXColor10308 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10320)
#declare LDXColor10320 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10321)
#declare LDXColor10321 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10322)
#declare LDXColor10322 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10323)
#declare LDXColor10323 = LDXOpaqueColor(1,0.501961,0)
#end

#ifndef (LDXColor10484)
#declare LDXColor10484 = LDXOpaqueColor(1,0.501961,0)
#end

#declare LDX_4_dash_4cyli_dot_dat_in_part = cylinder // Cylinder 1
{
	<0,0,0>,<0,1,0>,1 open
}

#declare LDX_4_dash_4cyli_dot_dat = cylinder // Cylinder 1
{
	<0,0,0>,<0,1,0>,1 open
}

#declare LDX_4_dash_4disc_dot_dat_in_part = disc // Disc 1
{
	<0,0,0>,<0,1,0>,1
}

#declare LDX_4_dash_4disc_dot_dat = disc // Disc 1
{
	<0,0,0>,<0,1,0>,1
}

#declare LDXLegoSpace = 49.5;
#declare LDXStudLogo =
union {
	merge {
		// L
		sphere {<-88,0,0>,4}
		cylinder {<-88,0,0>,<0,0,0>,4 open}
		sphere {<0,0,0>,4}
		cylinder {<0,0,0>,<0,0,25>,4 open}
		sphere {<0,0,25>,4}
		clipped_by {plane{y,0}}
	}

	merge {
		// E
		sphere {<-88,0,25>,4}
		cylinder {<-88,0,25>,<-88,0,0>,4 open}
		sphere {<-88,0,0>,4}
		cylinder {<-88,0,0>,<0,0,0>,4 open}
		sphere {<0,0,0>,4}
		cylinder {<0,0,0>,<0,0,25>,4 open}
		sphere {<0,0,25>,4}
		sphere {<-44,0,17>,4}
		cylinder {<-44,0,0>,<-44,0,17>,4 open}
		clipped_by {plane{y,0}}
		translate <0,0,LDXLegoSpace>
	}

	merge {
		// G
		sphere {<-74,0,25>,4}
		torus {12.5,4 clipped_by{plane{x,0}} translate<-74,0,12.5>}
		cylinder {<-74,0,0>,<-14,0,0>,4 open}
		torus {12.5,4 clipped_by{plane{-x,0}} translate<-14,0,12.5>}
		cylinder {<-14,0,25>,<-44,0,25>,4 open}
		sphere {<-44,0,25>,4}
		cylinder {<-44,0,25>,<-44,0,17>,4 open}
		sphere {<-44,0,17>,4}
		clipped_by {plane{y,0}}
		translate <0,0,LDXLegoSpace*2>
	}

	merge {
		// O
		torus {12.5,4 clipped_by{plane{x,0}} translate<-74,0,12.5>}
		cylinder {<-74,0,0>,<-14,0,0>,4 open}
		torus {12.5,4 clipped_by{plane{-x,0}} translate<-14,0,12.5>}
		cylinder {<-14,0,25>,<-74,0,25>,4 open}
		clipped_by {plane{y,0}}
		translate <0,0,LDXLegoSpace*3>
	}

	matrix <1,0,-0.22,0,1,0,0,0,1,0,0,0>
	scale .045
	translate <1.85,-4,-4.45>
}

#declare LDX_stud_dot_dat_in_part =
#if (LDXQual <= 2)
cylinder { <0,0,0>, <0,-4,0>, 6 }
#else
union {
	cylinder { <0,0,0>, <0,-4,0>, 6 }
	object { LDXStudLogo }
}
#end

#declare LDX_stud_dot_dat =
#if (LDXQual <= 2)
cylinder { <0,0,0>, <0,-4,0>, 6 }
#else
union {
	cylinder { <0,0,0>, <0,-4,0>, 6 }
	object { LDXStudLogo }
}
#end

#declare LDX_3005_dot_dat =
#if (LDXQual = 0)
box {
	<-10,-4,-10>,<10,24,10>
}
#else
union {
// Brick  1 x  1
// Name: 3005.dat
// Author: James Jessiman
// !LDRAW_ORG Part UPDATE 2002-03
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2001-10-26 [PTadmin] Official Update 2001-01
// !HISTORY 2002-05-07 [unknown] BFC Certification
// !HISTORY 2002-06-11 [PTadmin] Official Update 2002-03
// !HISTORY 2007-05-07 [PTadmin] Header formatted for Contributor Agreement
// !HISTORY 2008-07-01 [PTadmin] Official Update 2008-01
// BFC INVERTNEXT
	#if (LDXStuds)
		object {
			LDX_stud_dot_dat_in_part
			matrix <1,0,0,0,1,0,0,0,1,0,0,0>
		}
	#end // LDXStuds
	mesh2 {
		vertex_vectors {
			16,
			<-10,0,-10>, <-10,0,10>, <-10,24,-10>, <-10,24,10>,
			<-6,4,-6>, <-6,4,6>, <-6,24,-6>, <-6,24,6>,
			<6,4,-6>, <6,4,6>, <6,24,-6>, <6,24,6>,
			<10,0,-10>, <10,0,10>, <10,24,-10>, <10,24,10>
		}
		normal_vectors {
			5,
			<-1,0,0>, <0,-1,0>, <0,0,-1>, <0,0,1>,
			<1,0,0>
		}
		face_indices {
			28,
			<5, 9, 8>, <5, 8, 4>, <5, 7, 11>, <5, 11, 9>,
			<4, 6, 7>, <4, 7, 5>, <8, 10, 6>, <8, 6, 4>,
			<9, 11, 10>, <9, 10, 8>, <15, 11, 7>, <15, 7, 3>,
			<3, 7, 6>, <3, 6, 2>, <2, 6, 10>, <2, 10, 14>,
			<14, 10, 11>, <14, 11, 15>, <1, 13, 12>, <1, 12, 0>,
			<1, 3, 15>, <1, 15, 13>, <0, 2, 3>, <0, 3, 1>,
			<12, 14, 2>, <12, 2, 0>, <13, 15, 14>, <13, 14, 12>
		}
		normal_indices {
			28,
			<1, 1, 1>, <1, 1, 1>, <3, 3, 3>, <3, 3, 3>,
			<0, 0, 0>, <0, 0, 0>, <2, 2, 2>, <2, 2, 2>,
			<4, 4, 4>, <4, 4, 4>, <1, 1, 1>, <1, 1, 1>,
			<1, 1, 1>, <1, 1, 1>, <1, 1, 1>, <1, 1, 1>,
			<1, 1, 1>, <1, 1, 1>, <1, 1, 1>, <1, 1, 1>,
			<3, 3, 3>, <3, 3, 3>, <0, 0, 0>, <0, 0, 0>,
			<2, 2, 2>, <2, 2, 2>, <4, 4, 4>, <4, 4, 4>
		}
	}
}
#end

#declare LDX_every_color_dot_ldr = union {
// Every Color
// Name: every_color.ldr
// Author: MLCad
// Unofficial Model
// ROTATION CENTER 0 0 0 1 "Custom"
// ROTATION CONFIG 0 0
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor0 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor1 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor2 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor3 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor4 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor5 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor6 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor7 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor8 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor9 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor11 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor12 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor13 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor14 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor15 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor17 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor18 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor19 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor20 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor21 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor22 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor23 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor24 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor25 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor26 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor27 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor28 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor29 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor30 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor31 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor32 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor33 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor34 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor35 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor36 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor37 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor38 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor39 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor40 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor41 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor42 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor43 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor44 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor45 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor46 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor47 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor52 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor54 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor57 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor60 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor61 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor62 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor63 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor64 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor65 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor66 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor67 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor68 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor69 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor70 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor71 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor72 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor73 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor74 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor75 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor76 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor77 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor78 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor79 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor80 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor81 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor82 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor83 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor84 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor85 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor86 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor87 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor89 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor92 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor100 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor110 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor112 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor114 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor115 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor117 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor118 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor120 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor125 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor128 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor129 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor132 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor133 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor134 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor135 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor137 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor142 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor148 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor150 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor151 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor178 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor179 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor183 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor184 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor186 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor189 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor191 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor212 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor216 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor218 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor219 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor226 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor231 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor232 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor234 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor256 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor272 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor273 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor284 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor285 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor288 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor293 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor294 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor295 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor297 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor300 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor302 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor308 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor313 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor320 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor321 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor322 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor323 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor324 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor326 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor329 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor330 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor334 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor335 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor339 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor350 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor351 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor353 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor366 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor373 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor375 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor378 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor379 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor383 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor406 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor449 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor450 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor462 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor484 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor490 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor493 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor494 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor495 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor496 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor503 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor504 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor507 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor508 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor509 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor511 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10002 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10026 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10031 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10070 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10226 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10308 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10320 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10321 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10322 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10323 }
	}
	object {
		LDX_3005_dot_dat
		LDXSeamMatrix(20, 28, 20, 0, 10, 0)
		matrix <1,0,0,0,1,0,0,0,1,0,-24,0>
		#if (version >= 3.1) material #else texture #end { LDXColor10484 }
	}
#if (LDXRefls = 0)
	no_reflection
#end
#if (LDXShads = 0)
	no_shadow
#end
}

// every_color.ldr
object {
	LDX_every_color_dot_ldr
	#if (version >= 3.1) material #else texture #end { LDXColor7 }
}

// Floor
#if (LDXFloor != 0)
object {
	plane { LDXFloorAxis, LDXFloorLoc hollow }
	texture {
#if (version >= 3.7)
		pigment { color srgb <LDXFloorR,LDXFloorG,LDXFloorB> }
#else
		pigment { color rgb <LDXFloorR,LDXFloorG,LDXFloorB> }
#end
		finish { ambient LDXFloorAmb diffuse LDXFloorDif }
	}
}
#end

